import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { NativeModules, Platform } from 'react-native';

export type Language = 'en' | 'pt' | 'es' | 'fr' | 'de' | 'it';

// Função para detectar o idioma do dispositivo
const getDeviceLanguage = (): Language => {
  let locale: string = 'en';
  
  try {
    // Tentar usar Intl API (mais confiável e funciona em todas as plataformas)
    if (typeof Intl !== 'undefined' && Intl.DateTimeFormat) {
      const resolved = Intl.DateTimeFormat().resolvedOptions();
      locale = resolved.locale || resolved.language || 'en';
    }
    
    // Fallback para NativeModules se Intl não funcionar ou retornar 'en'
    // Mas também tentar sempre NativeModules para ter certeza
    if (Platform.OS === 'ios') {
      const SettingsManager = NativeModules.SettingsManager;
      if (SettingsManager?.settings) {
        const iosLocale = SettingsManager.settings.AppleLocale || 
                 SettingsManager.settings.AppleLanguages?.[0];
        if (iosLocale && iosLocale !== 'en') {
          locale = iosLocale;
        }
      }
    } else if (Platform.OS === 'android') {
      const I18nManager = NativeModules.I18nManager;
      if (I18nManager?.localeIdentifier) {
        const androidLocale = I18nManager.localeIdentifier;
        if (androidLocale && androidLocale !== 'en') {
          locale = androidLocale;
        }
      }
    }
  } catch (error) {
    locale = 'en';
  }
  
  const languageCode = locale.split('-')[0].split('_')[0].toLowerCase();
  const supportedLanguages: Language[] = ['en', 'pt', 'es', 'fr', 'de', 'it'];
  if (supportedLanguages.includes(languageCode as Language)) {
    return languageCode as Language;
  }
  return 'en';
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traduções
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.chat': 'Chat',
    'nav.add': 'Add',
    'nav.profile': 'Profile',
    'nav.progress': 'Progress',
    
    // Welcome Screen
    'welcome.title': 'Welcome to Nuti',
    'welcome.subtitle': 'Your personal nutrition assistant',
    'welcome.getStarted': 'Get Started',
    'welcome.alreadyRegistered': 'Already registered? Sign in',
    'welcome.selectLanguage': 'Select Language',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Name',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.continueWithEmail': 'Continue with Email',
    'auth.or': 'or',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.wrongMethod': 'This account was created with {method}. Please use {method} to sign in.',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.weakPassword': 'Password should be at least 6 characters',
    'auth.emailInUse': 'This email is already in use',
    
    // Onboarding
    'onboarding.gender': 'Gender',
    'onboarding.gender.male': 'Male',
    'onboarding.gender.female': 'Female',
    'onboarding.genderDescription': 'This helps us personalize your experience',
    'onboarding.workoutsPerWeek': 'How many workouts per week?',
    'onboarding.workoutsPerWeekDescription': 'This helps us calculate your calorie needs',
    'onboarding.workouts.0-2': '0-2',
    'onboarding.workouts.0-2.description': 'Sedentary',
    'onboarding.workouts.3-6': '3-6',
    'onboarding.workouts.3-6.description': 'Moderately Active',
    'onboarding.workouts.6+': '6+',
    'onboarding.workouts.6+.description': 'Very Active',
    'onboarding.heardFrom': 'Where did you hear about us?',
    'onboarding.heardFrom.social': 'Social Media',
    'onboarding.heardFrom.friends': 'Friends',
    'onboarding.heardFrom.other': 'Other',
    'onboarding.triedOtherApps': 'Have you tried other nutrition apps?',
    'onboarding.triedOtherApps.yes': 'Yes',
    'onboarding.triedOtherApps.no': 'No',
    'onboarding.height': 'Height',
    'onboarding.heightQuestion': 'What is your height?',
    'onboarding.heightDescription': 'This will be used to calibrate your custom plan.',
    'onboarding.weight': 'Weight',
    'onboarding.weightQuestion': 'What is your weight?',
    'onboarding.weightDescription': 'This will be used to calibrate your custom plan.',
    'onboarding.age': 'Age',
    'onboarding.ageQuestion': 'What is your age?',
    'onboarding.ageDescription': 'This will be used to calibrate your custom plan.',
    'onboarding.yearsOld': 'years old',
    'onboarding.goal': 'What is your goal?',
    'onboarding.goalDescription': 'This helps us generate a plan for your calorie intake.',
    'onboarding.goal.lose': 'Lose Weight',
    'onboarding.goal.maintain': 'Maintain Weight',
    'onboarding.goal.gain': 'Gain Weight',
    'onboarding.desiredWeight': 'Desired Weight',
    'onboarding.desiredWeightQuestion': 'What is your desired weight?',
    'onboarding.currentWeight': 'Current weight',
    'onboarding.desiredWeightHintGain': 'To gain weight, the desired weight must be greater than {weight} {unit}',
    'onboarding.desiredWeightHintLose': 'To lose weight, the desired weight must be less than {weight} {unit}',
    'onboarding.desiredWeightErrorGain': 'The desired weight must be greater than {weight} {unit}',
    'onboarding.desiredWeightErrorLose': 'The desired weight must be less than {weight} {unit}',
    'onboarding.referralCode': 'Referral Code',
    'onboarding.referralCodeQuestion': 'Do you have a referral code? (Optional)',
    'onboarding.referralCode.placeholder': 'Enter referral code',
    'onboarding.referralCode.paste': 'Paste',
    'onboarding.referralCode.skip': "You can skip this step if you don't have a code",
    'onboarding.referralCode.pasted': 'Code pasted!',
    'onboarding.referralCode.pastedMessage': 'Referral code has been pasted',
    'onboarding.referralCode.empty': 'No content',
    'onboarding.referralCode.emptyMessage': 'Clipboard is empty',
    'onboarding.referralCode.error': 'Error',
    'onboarding.referralCode.errorMessage': 'Failed to paste from clipboard',
    'onboarding.referralCode.clipboardNotAvailable': 'Clipboard not available',
    'onboarding.referralCode.clipboardNotAvailableMessage': 'Please rebuild the app to enable clipboard paste. For now, you can type the code manually.',
    'onboarding.calorieGoal': 'Your Daily Calorie Goal',
    'onboarding.calorieGoalDescription': 'Based on your profile, this is the number of calories you should consume daily to reach your goal.',
    'onboarding.kcalPerDay': 'kcal per day',
    'onboarding.calculating': 'Calculating your plan...',
    'onboarding.calculatingDescription': 'We\'re preparing your personalized nutrition plan',
    'onboarding.macros': 'Macronutrients',
    'onboarding.protein': 'Protein',
    'onboarding.carbs': 'Carbohydrates',
    'onboarding.fat': 'Fat',
    'onboarding.metabolicInfo': 'Metabolic Information',
    'onboarding.bmr': 'Basal Metabolic Rate (BMR)',
    'onboarding.tdee': 'Total Daily Energy Expenditure (TDEE)',
    'onboarding.premiumTitle': 'Unlock Premium',
    'onboarding.premiumDescription': 'Get access to advanced features and unlock your full potential!',
    'onboarding.premiumButton': 'Upgrade to Premium',
    'onboarding.premiumSkip': 'Maybe later',
    'onboarding.premiumFeature1': 'Unlimited AI Chat',
    'onboarding.premiumFeature2': 'Advanced Analytics & Reports',
    'onboarding.premiumFeature3': 'Unlimited Meal Tracking',
    'onboarding.premiumFeature4': 'Exclusive Badges & Achievements',
    'onboarding.premiumFeature5': 'Cloud Sync Across Devices',
    'onboarding.premiumFeature6': 'Priority Support',
    'onboarding.rateAppTitle': 'Rate Us!',
    'onboarding.rateAppDescription': 'If you\'re enjoying Nuti, please take a moment to rate us on the Play Store!',
    'onboarding.rateAppButton': 'Rate on Play Store',
    'onboarding.rateAppSkip': 'Maybe later',
    'onboarding.createAccount': 'Create Account',
    'onboarding.createAccountTitle': 'Create your account',
    'onboarding.createAccountDescription': 'Choose how you want to create your account',
    'onboarding.metric': 'Metric',
    'onboarding.imperial': 'Imperial',
    'onboarding.metricCm': 'Metric (cm)',
    'onboarding.imperialFtIn': 'Imperial (ft/in)',
    'onboarding.metricKg': 'Metric (kg)',
    'onboarding.imperialLbs': 'Imperial (lbs)',
    'onboarding.back': 'Back',
    'onboarding.continue': 'Continue',
    'onboarding.cancel': 'Cancel',
    'onboarding.error': 'Error',
    'onboarding.errorFillAllFields': 'Please fill in all fields',
    'onboarding.errorPasswordsDontMatch': 'Passwords do not match',
    'onboarding.errorPasswordTooShort': 'Password must be at least 6 characters',
    
    // Dashboard
    'dashboard.greeting': 'Hello, {name}!',
    'dashboard.howIsDay': 'How is your day going?',
    'dashboard.caloriesConsumed': 'Consumed',
    'dashboard.caloriesRemaining': 'Remaining',
    'dashboard.caloriesGoal': 'Goal',
    'dashboard.mealsToday': 'Meals Today',
    'dashboard.noMeals': "You haven't registered any meals today yet.",
    'dashboard.addFirstMeal': 'Add your first meal!',
    'dashboard.streak': 'Day Streak',
    'dashboard.badges': 'Badges',
    'dashboard.protein': 'Protein',
    'dashboard.carbs': 'Carbs',
    'dashboard.fat': 'Fat',
    'dashboard.water': 'Water',
    'dashboard.addWater': 'Add Water',
    'dashboard.editWater': 'Edit Water',
    'dashboard.waterAmount': 'Amount',
    'dashboard.waterTotal': 'Total Amount',
    'dashboard.waterAdded': 'Water Added',
    'dashboard.waterAddedMessage': 'added successfully',
    'dashboard.waterUpdated': 'Water Updated',
    'dashboard.waterUpdatedMessage': 'Water amount updated successfully',
    'dashboard.waterInvalidAmount': 'Please enter a valid amount',
    'dashboard.waterError': 'Error adding water. Please try again.',
    'dashboard.add': 'Add',
    'dashboard.deleteMeal': 'Delete Meal',
    'dashboard.deleteMealConfirm': 'Are you sure you want to delete this meal?',
    'dashboard.delete': 'Delete',
    'dashboard.mealDeleted': 'Meal Deleted',
    'dashboard.mealDeletedMessage': 'The meal has been deleted successfully.',
    'dashboard.deleteMealError': 'Error deleting meal. Please try again.',
    'dashboard.mealType': 'Meal Type',
    'dashboard.dateTime': 'Date & Time',
    'dashboard.calories': 'Calories',
    'dashboard.macros': 'Macronutrients',
    'dashboard.today': 'Today',
    
    // Progress
    'progress.title': 'Progress',
    'progress.subtitle': 'Track your daily progress',
    'progress.caloriesToday': 'Calories Today',
    'progress.dailyGoal': 'Daily goal',
    'progress.configureGoal': 'Configure your calorie goal in profile',
    'progress.statistics': 'Statistics',
    'progress.currentWeight': 'Current weight',
    'progress.height': 'Height',
    'progress.myWeight': 'My weight',
    'progress.goal': 'Goal',
    'progress.nextWeighIn': 'Next weigh-in',
    'progress.dayStreak': 'Day streak',
    'progress.90Days': '90 Days',
    'progress.6Months': '6 Months',
    'progress.1Year': '1 Year',
    'progress.allTime': 'All time...',
    'progress.goalProgress': 'Goal Progress',
    'progress.ofGoal': 'of goal',
    'progress.motivationalMessage': 'Starting is the hardest part. You are ready for this!',
    
    // Chat
    'chat.title': 'Ajuda Nuti',
    'chat.subtitle': 'Your nutrition assistant',
    'chat.placeholder': 'Type your message...',
    'chat.loading': 'Loading...',
    'chat.greeting': 'Hello!',
    'chat.greetingMessage': "I'm here to help you with your nutrition journey. How can I assist you today?",
    'chat.limitReached': 'Limit reached',
    'chat.limitMessage': 'Upgrade to Premium for unlimited chat!',
    'chat.error': 'Error',
    'chat.errorMessage': 'Error communicating with AI',
    'chat.retry': 'Please try again.',
    
    // Add Meal
    'addMeal.title': 'Add Meal',
    'addMeal.camera': 'Take Photo',
    'addMeal.cameraDescription': 'Take a photo of your meal',
    'addMeal.barcode': 'Scan Barcode',
    'addMeal.barcodeDescription': 'Scan product barcode',
    'addMeal.search': 'Search Food',
    'addMeal.searchDescription': 'Search for food manually',
    'addMeal.editFood': 'Edit Food',
    'addMeal.editFoodDescription': 'Review and edit the identified information',
    'addMeal.mealType': 'Meal Type',
    'addMeal.breakfast': 'Breakfast',
    'addMeal.lunch': 'Lunch',
    'addMeal.dinner': 'Dinner',
    'addMeal.snack': 'Snack',
    'addMeal.foodName': 'Food Name',
    'addMeal.foodNamePlaceholder': 'Food name',
    'addMeal.calories': 'Calories',
    'addMeal.protein': 'Protein',
    'addMeal.carbs': 'Carbs',
    'addMeal.fat': 'Fat',
    'addMeal.saveMeal': 'Add Meal',
    'addMeal.weight': 'Weight',
    'addMeal.weightDescription': 'Adjust the weight to recalculate nutritional values',
    'addMeal.plateFoods': 'Foods on Plate',
    'addMeal.nutritionalValues': 'Nutritional Values',
    'addMeal.analyzing': 'Analyzing image...',
    'addMeal.error': 'Error',
    'addMeal.errorProcessing': 'Error processing image. Please try again.',
    'addMeal.errorNotFood': 'This image does not contain food. Please upload an image of food.',
    
    // Profile
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.language': 'Language',
    'profile.edit': 'Edit',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.name': 'Name',
    'profile.weight': 'Weight',
    'profile.height': 'Height',
    'profile.goal': 'Goal',
    'profile.badges': 'Unlocked Badges',
    'profile.streak': 'Current Streak',
    'profile.streakDays': 'consecutive days',
    'profile.plan': 'Current Plan',
    'profile.plan.free': 'Free',
    'profile.plan.premium': '⭐ Premium',
    'profile.upgradePremium': 'Upgrade to Premium',
    'profile.referralCode.title': 'Referral Code',
    'profile.referralCode.description': 'Share your code with friends and earn rewards',
    'profile.referralCode.copied': 'Code Copied!',
    'profile.referralCode.copiedMessage': 'Referral code has been copied to clipboard',
    'profile.referralCode.copyError': 'Error copying code',
    'profile.signOut': 'Sign Out',
    'profile.signOutConfirm': 'Are you sure you want to sign out?',
    'profile.signOutConfirmYes': 'Sign Out',
    'profile.signOutConfirmNo': 'Cancel',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.updateError': 'Error updating profile',
    'profile.settings': 'Settings',
    'profile.settings.notifications': 'Notifications',
    'profile.settings.privacy': 'Privacy',
    'profile.settings.about': 'About',
    'profile.settings.terms': 'Terms & Conditions',
    'profile.settings.privacyPolicy': 'Privacy Policy',
    'profile.settings.version': 'Version',
    'profile.settings.help': 'Help & Support',
    'profile.settings.feedback': 'Send Feedback',
    'profile.settings.madeWith': 'Made with ❤️ for your health',
    'profile.settings.dataSecure': 'Your data is secure',
    'profile.settings.supportEmail': 'Support Email',
    'profile.settings.featureRequest': 'Feature Request',
    'profile.settings.deleteAccount': 'Delete Account?',
    'profile.settings.deleteAccountConfirm': 'Are you sure you want to delete your account? This action cannot be undone.',
    'profile.settings.delete': 'Delete',
    'profile.personalDetails': 'Personal Details',
    'profile.goalAndWeight': 'Goal and Current Weight',
    'profile.preferences': 'Preferences',
    'profile.age': 'years old',
    'profile.referralCode.invite': 'Invite a friend to earn $',
    'profile.editName': 'Edit Name',
    'profile.namePlaceholder': 'Enter your name here',
    'profile.done': 'Done',
    'profile.nameRequired': 'Please enter a name',
    'profile.nameUpdated': 'Name updated successfully',
    'profile.detailsUpdated': 'Details updated successfully',
    'profile.fillAllFields': 'Please fill in all fields',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.chat': 'Chat',
    'nav.add': 'Adicionar',
    'nav.profile': 'Perfil',
    'nav.progress': 'Progresso',
    
    // Welcome Screen
    'welcome.title': 'Bem-vindo ao Nuti',
    'welcome.subtitle': 'O teu assistente nutricional pessoal',
    'welcome.getStarted': 'Começar',
    'welcome.alreadyRegistered': 'Já tens conta? Inicia sessão',
    'welcome.selectLanguage': 'Selecionar Idioma',
    
    // Auth
    'auth.signIn': 'Iniciar Sessão',
    'auth.signUp': 'Registar',
    'auth.email': 'Email',
    'auth.password': 'Palavra-passe',
    'auth.confirmPassword': 'Confirmar Palavra-passe',
    'auth.name': 'Nome',
    'auth.continueWithGoogle': 'Continuar com Google',
    'auth.continueWithEmail': 'Continuar com Email',
    'auth.or': 'ou',
    'auth.noAccount': 'Não tens conta?',
    'auth.hasAccount': 'Já tens conta?',
    'auth.wrongMethod': 'Esta conta foi criada com {method}. Por favor, usa {method} para iniciar sessão.',
    'auth.invalidCredentials': 'Email ou palavra-passe inválidos',
    'auth.passwordMismatch': 'As palavras-passe não coincidem',
    'auth.weakPassword': 'A palavra-passe deve ter pelo menos 6 caracteres',
    'auth.emailInUse': 'Este email já está em uso',
    
    // Onboarding
    'onboarding.gender': 'Género',
    'onboarding.gender.male': 'Masculino',
    'onboarding.gender.female': 'Feminino',
    'onboarding.genderDescription': 'Isto ajuda-nos a personalizar a tua experiência',
    'onboarding.workoutsPerWeek': 'Quantos treinos por semana?',
    'onboarding.workoutsPerWeekDescription': 'Isto ajuda-nos a calcular as tuas necessidades calóricas',
    'onboarding.workouts.0-2': '0-2',
    'onboarding.workouts.0-2.description': 'Sedentário',
    'onboarding.workouts.3-6': '3-6',
    'onboarding.workouts.3-6.description': 'Moderadamente Ativo',
    'onboarding.workouts.6+': '6+',
    'onboarding.workouts.6+.description': 'Muito Ativo',
    'onboarding.heardFrom': 'Onde ouviste falar de nós?',
    'onboarding.heardFrom.social': 'Redes Sociais',
    'onboarding.heardFrom.friends': 'Amigos',
    'onboarding.heardFrom.other': 'Outro',
    'onboarding.triedOtherApps': 'Já experimentaste outras apps de nutrição?',
    'onboarding.triedOtherApps.yes': 'Sim',
    'onboarding.triedOtherApps.no': 'Não',
    'onboarding.height': 'Altura',
    'onboarding.heightQuestion': 'Qual é a tua altura?',
    'onboarding.heightDescription': 'Isto será usado para calibrar o teu plano personalizado.',
    'onboarding.weight': 'Peso',
    'onboarding.weightQuestion': 'Qual é o teu peso?',
    'onboarding.weightDescription': 'Isto será usado para calibrar o teu plano personalizado.',
    'onboarding.age': 'Idade',
    'onboarding.ageQuestion': 'Qual é a tua idade?',
    'onboarding.ageDescription': 'Isto será usado para calibrar o teu plano personalizado.',
    'onboarding.yearsOld': 'anos',
    'onboarding.goal': 'Qual é o teu objetivo?',
    'onboarding.goalDescription': 'Isto ajuda-nos a gerar um plano para a tua ingestão calórica.',
    'onboarding.goal.lose': 'Perder Peso',
    'onboarding.goal.maintain': 'Manter Peso',
    'onboarding.goal.gain': 'Ganhar Peso',
    'onboarding.desiredWeight': 'Peso Desejado',
    'onboarding.desiredWeightQuestion': 'Qual é o teu peso desejado?',
    'onboarding.currentWeight': 'Peso atual',
    'onboarding.desiredWeightHintGain': 'Para ganhar peso, o peso desejado deve ser maior que {weight} {unit}',
    'onboarding.desiredWeightHintLose': 'Para perder peso, o peso desejado deve ser menor que {weight} {unit}',
    'onboarding.desiredWeightErrorGain': 'O peso desejado deve ser maior que {weight} {unit}',
    'onboarding.desiredWeightErrorLose': 'O peso desejado deve ser menor que {weight} {unit}',
    'onboarding.referralCode': 'Código de Referência',
    'onboarding.referralCodeQuestion': 'Tens um código de referência? (Opcional)',
    'onboarding.referralCode.placeholder': 'Inserir código de referência',
    'onboarding.referralCode.paste': 'Colar',
    'onboarding.referralCode.skip': 'Podes saltar este passo se não tiveres um código',
    'onboarding.referralCode.pasted': 'Código colado!',
    'onboarding.referralCode.pastedMessage': 'O código de referência foi colado',
    'onboarding.referralCode.empty': 'Sem conteúdo',
    'onboarding.referralCode.emptyMessage': 'A área de transferência está vazia',
    'onboarding.referralCode.error': 'Erro',
    'onboarding.referralCode.errorMessage': 'Falha ao colar da área de transferência',
    'onboarding.referralCode.clipboardNotAvailable': 'Área de transferência não disponível',
    'onboarding.referralCode.clipboardNotAvailableMessage': 'Por favor, reconstrói a app para ativar a colagem. Por agora, podes escrever o código manualmente.',
    'onboarding.calorieGoal': 'A Tua Meta Diária de Calorias',
    'onboarding.calorieGoalDescription': 'Baseado no teu perfil, este é o número de calorias que deves consumir diariamente para atingir o teu objetivo.',
    'onboarding.kcalPerDay': 'kcal por dia',
    'onboarding.calculating': 'A calcular o teu plano...',
    'onboarding.calculatingDescription': 'Estamos a preparar o teu plano nutricional personalizado',
    'onboarding.macros': 'Macronutrientes',
    'onboarding.protein': 'Proteína',
    'onboarding.carbs': 'Carboidratos',
    'onboarding.fat': 'Gordura',
    'onboarding.metabolicInfo': 'Informação Metabólica',
    'onboarding.bmr': 'Taxa Metabólica Basal (BMR)',
    'onboarding.tdee': 'Gasto Energético Total Diário (TDEE)',
    'onboarding.premiumTitle': 'Desbloqueia Premium',
    'onboarding.premiumDescription': 'Obtém acesso a funcionalidades avançadas e desbloqueia o teu potencial completo!',
    'onboarding.premiumButton': 'Atualizar para Premium',
    'onboarding.premiumSkip': 'Talvez mais tarde',
    'onboarding.premiumFeature1': 'Chat Ilimitado',
    'onboarding.premiumFeature2': 'Análises e Relatórios Avançados',
    'onboarding.premiumFeature3': 'Rastreamento Ilimitado de Refeições',
    'onboarding.premiumFeature4': 'Badges e Conquistas Exclusivas',
    'onboarding.premiumFeature5': 'Sincronização na Nuvem',
    'onboarding.premiumFeature6': 'Suporte Prioritário',
    'onboarding.rateAppTitle': 'Avalia-nos!',
    'onboarding.rateAppDescription': 'Se estás a gostar do Nuti, por favor, tira um momento para nos avaliar na Play Store!',
    'onboarding.rateAppButton': 'Avaliar na Play Store',
    'onboarding.rateAppSkip': 'Talvez mais tarde',
    'onboarding.createAccount': 'Criar Conta',
    'onboarding.createAccountTitle': 'Cria a tua conta',
    'onboarding.createAccountDescription': 'Escolhe como queres criar a tua conta',
    'onboarding.metric': 'Métrico',
    'onboarding.imperial': 'Imperial',
    'onboarding.metricCm': 'Métrico (cm)',
    'onboarding.imperialFtIn': 'Imperial (pés/polegadas)',
    'onboarding.metricKg': 'Métrico (kg)',
    'onboarding.imperialLbs': 'Imperial (lbs)',
    'onboarding.back': 'Voltar',
    'onboarding.continue': 'Continuar',
    'onboarding.cancel': 'Cancelar',
    'onboarding.error': 'Erro',
    'onboarding.errorFillAllFields': 'Por favor, preenche todos os campos',
    'onboarding.errorPasswordsDontMatch': 'As passwords não coincidem',
    'onboarding.errorPasswordTooShort': 'A password deve ter pelo menos 6 caracteres',
    
    // Dashboard
    'dashboard.greeting': 'Olá, {name}!',
    'dashboard.howIsDay': 'Como está a correr o teu dia?',
    'dashboard.caloriesConsumed': 'Consumidas',
    'dashboard.caloriesRemaining': 'Restantes',
    'dashboard.caloriesGoal': 'Meta',
    'dashboard.mealsToday': 'Refeições de Hoje',
    'dashboard.noMeals': 'Ainda não registaste refeições hoje.',
    'dashboard.addFirstMeal': 'Adiciona a tua primeira refeição!',
    'dashboard.streak': 'Dias Consecutivos',
    'dashboard.badges': 'Badges',
    'dashboard.protein': 'Proteína',
    'dashboard.carbs': 'Carboidratos',
    'dashboard.fat': 'Gordura',
    'dashboard.water': 'Água',
    'dashboard.addWater': 'Adicionar Água',
    'dashboard.editWater': 'Editar Água',
    'dashboard.waterAmount': 'Quantidade',
    'dashboard.waterTotal': 'Quantidade Total',
    'dashboard.waterAdded': 'Água Adicionada',
    'dashboard.waterAddedMessage': 'adicionada com sucesso',
    'dashboard.waterUpdated': 'Água Atualizada',
    'dashboard.waterUpdatedMessage': 'Quantidade de água atualizada com sucesso',
    'dashboard.waterInvalidAmount': 'Por favor, insere uma quantidade válida',
    'dashboard.waterError': 'Erro ao adicionar água. Por favor, tenta novamente.',
    'dashboard.add': 'Adicionar',
    'dashboard.deleteMeal': 'Eliminar Refeição',
    'dashboard.deleteMealConfirm': 'Tens a certeza que queres eliminar esta refeição?',
    'dashboard.delete': 'Eliminar',
    'dashboard.mealDeleted': 'Refeição Eliminada',
    'dashboard.mealDeletedMessage': 'A refeição foi eliminada com sucesso.',
    'dashboard.deleteMealError': 'Erro ao eliminar refeição. Por favor, tenta novamente.',
    'dashboard.mealType': 'Tipo de Refeição',
    'dashboard.dateTime': 'Data e Hora',
    'dashboard.calories': 'Calorias',
    'dashboard.macros': 'Macronutrientes',
    'dashboard.today': 'Hoje',
    
    // Progress
    'progress.title': 'Progresso',
    'progress.subtitle': 'Acompanhe o seu progresso diário',
    'progress.caloriesToday': 'Calorias Hoje',
    'progress.dailyGoal': 'Meta diária',
    'progress.configureGoal': 'Configure a sua meta de calorias no perfil',
    'progress.statistics': 'Estatísticas',
    'progress.currentWeight': 'Peso atual',
    'progress.height': 'Altura',
    'progress.myWeight': 'Meu peso',
    'progress.goal': 'Meta',
    'progress.nextWeighIn': 'Próxima pesagem',
    'progress.dayStreak': 'Sequência de dias',
    'progress.90Days': '90 Dias',
    'progress.6Months': '6 Meses',
    'progress.1Year': '1 Ano',
    'progress.allTime': 'Todos os tem...',
    'progress.goalProgress': 'Progresso do Objetivo',
    'progress.ofGoal': 'da meta',
    'progress.motivationalMessage': 'Começar é a parte mais difícil. Você está pronto para isso!',
    
    // Chat
    'chat.title': 'Ajuda Nuti',
    'chat.subtitle': 'O teu assistente nutricional',
    'chat.placeholder': 'Escreve a tua mensagem...',
    'chat.loading': 'A carregar...',
    'chat.greeting': 'Olá!',
    'chat.greetingMessage': 'Estou aqui para te ajudar na tua jornada nutricional. Como posso ajudar hoje?',
    'chat.limitReached': 'Limite atingido',
    'chat.limitMessage': 'Atualiza para Premium para chat ilimitado!',
    'chat.error': 'Erro',
    'chat.errorMessage': 'Erro ao comunicar com a IA',
    'chat.retry': 'Por favor, tenta novamente.',
    
    // Add Meal
    'addMeal.title': 'Adicionar Refeição',
    'addMeal.camera': 'Tirar Foto',
    'addMeal.cameraDescription': 'Tira uma foto da tua refeição',
    'addMeal.barcode': 'Ler Código de Barras',
    'addMeal.barcodeDescription': 'Lê o código de barras do produto',
    'addMeal.search': 'Pesquisar Alimento',
    'addMeal.searchDescription': 'Pesquisa manualmente por alimentos',
    'addMeal.editFood': 'Editar Alimento',
    'addMeal.editFoodDescription': 'Revisa e edita as informações identificadas',
    'addMeal.mealType': 'Tipo de Refeição',
    'addMeal.breakfast': 'Pequeno-almoço',
    'addMeal.lunch': 'Almoço',
    'addMeal.dinner': 'Jantar',
    'addMeal.snack': 'Lanche',
    'addMeal.foodName': 'Nome do Alimento',
    'addMeal.foodNamePlaceholder': 'Nome do alimento',
    'addMeal.calories': 'Calorias',
    'addMeal.protein': 'Proteína',
    'addMeal.carbs': 'Carboidratos',
    'addMeal.fat': 'Gordura',
    'addMeal.saveMeal': 'Adicionar Refeição',
    'addMeal.weight': 'Peso',
    'addMeal.weightDescription': 'Ajusta o peso para recalcular os valores nutricionais',
    'addMeal.plateFoods': 'Alimentos no Prato',
    'addMeal.nutritionalValues': 'Valores Nutricionais',
    'addMeal.analyzing': 'A analisar imagem...',
    'addMeal.error': 'Erro',
    'addMeal.errorProcessing': 'Erro ao processar imagem. Por favor, tenta novamente.',
    'addMeal.errorNotFood': 'Esta imagem não contém comida. Por favor, envia uma imagem de comida.',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.language': 'Idioma',
    'profile.edit': 'Editar',
    'profile.save': 'Guardar',
    'profile.cancel': 'Cancelar',
    'profile.name': 'Nome',
    'profile.weight': 'Peso',
    'profile.height': 'Altura',
    'profile.goal': 'Objetivo',
    'profile.badges': 'Badges Desbloqueadas',
    'profile.streak': 'Streak Atual',
    'profile.streakDays': 'dias consecutivos',
    'profile.plan': 'Plano Atual',
    'profile.plan.free': 'Free',
    'profile.plan.premium': '⭐ Premium',
    'profile.upgradePremium': 'Atualizar para Premium',
    'profile.referralCode.title': 'Código de Referência',
    'profile.referralCode.description': 'Partilha o teu código com amigos e ganha recompensas',
    'profile.referralCode.copied': 'Código Copiado!',
    'profile.referralCode.copiedMessage': 'O código de referência foi copiado para a área de transferência',
    'profile.referralCode.copyError': 'Erro ao copiar código',
    'profile.signOut': 'Sair',
    'profile.signOutConfirm': 'Tens a certeza que queres sair?',
    'profile.signOutConfirmYes': 'Sair',
    'profile.signOutConfirmNo': 'Cancelar',
    'profile.updateSuccess': 'Perfil atualizado com sucesso',
    'profile.updateError': 'Erro ao atualizar perfil',
    'profile.settings': 'Configurações',
    'profile.settings.notifications': 'Notificações',
    'profile.settings.privacy': 'Privacidade',
    'profile.settings.about': 'Sobre',
    'profile.settings.terms': 'Termos e Condições',
    'profile.settings.privacyPolicy': 'Política de Privacidade',
    'profile.settings.version': 'Versão',
    'profile.settings.help': 'Ajuda e Suporte',
    'profile.settings.feedback': 'Enviar Feedback',
    'profile.settings.madeWith': 'Feito com ❤️ para a tua saúde',
    'profile.settings.dataSecure': 'Os teus dados estão seguros',
    'profile.settings.supportEmail': 'Email de Suporte',
    'profile.settings.featureRequest': 'Solicitação de recurso',
    'profile.settings.deleteAccount': 'Excluir Conta?',
    'profile.settings.deleteAccountConfirm': 'Tens a certeza que queres eliminar a tua conta? Esta ação não pode ser desfeita.',
    'profile.settings.delete': 'Eliminar',
    'profile.personalDetails': 'Detalhes pessoais',
    'profile.goalAndWeight': 'Meta e peso atual',
    'profile.preferences': 'Preferências',
    'profile.age': 'anos',
    'profile.referralCode.invite': 'Invita un amico per guadagnare $',
    'profile.editName': 'Editar nome',
    'profile.namePlaceholder': 'Insira o nome aqui',
    'profile.done': 'Pronto',
    'profile.nameRequired': 'Por favor, insira um nome',
    'profile.nameUpdated': 'Nome atualizado com sucesso',
    'profile.detailsUpdated': 'Detalhes atualizados com sucesso',
    'profile.fillAllFields': 'Por favor, preencha todos os campos',
    
    // Common
    'common.loading': 'A carregar...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Fechar',
    'common.yes': 'Sim',
    'common.no': 'Não',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.chat': 'Chat',
    'nav.add': 'Añadir',
    'nav.profile': 'Perfil',
    'nav.progress': 'Progreso',
    
    // Welcome Screen
    'welcome.title': 'Bienvenido a Nuti',
    'welcome.subtitle': 'Tu asistente nutricional personal',
    'welcome.getStarted': 'Comenzar',
    'welcome.alreadyRegistered': '¿Ya tienes cuenta? Inicia sesión',
    'welcome.selectLanguage': 'Seleccionar Idioma',
    
    // Auth
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.name': 'Nombre',
    'auth.continueWithGoogle': 'Continuar con Google',
    'auth.continueWithEmail': 'Continuar con Correo',
    'auth.or': 'o',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.wrongMethod': 'Esta cuenta fue creada con {method}. Por favor, usa {method} para iniciar sesión.',
    'auth.invalidCredentials': 'Correo o contraseña inválidos',
    'auth.passwordMismatch': 'Las contraseñas no coinciden',
    'auth.weakPassword': 'La contraseña debe tener al menos 6 caracteres',
    'auth.emailInUse': 'Este correo ya está en uso',
    
    // Onboarding
    'onboarding.gender': 'Género',
    'onboarding.gender.male': 'Masculino',
    'onboarding.gender.female': 'Femenino',
    'onboarding.genderDescription': 'Esto nos ayuda a personalizar tu experiencia',
    'onboarding.workoutsPerWeek': '¿Cuántos entrenamientos por semana?',
    'onboarding.workoutsPerWeekDescription': 'Esto nos ayuda a calcular tus necesidades calóricas',
    'onboarding.workouts.0-2': '0-2',
    'onboarding.workouts.0-2.description': 'Sedentario',
    'onboarding.workouts.3-6': '3-6',
    'onboarding.workouts.3-6.description': 'Moderadamente Activo',
    'onboarding.workouts.6+': '6+',
    'onboarding.workouts.6+.description': 'Muy Activo',
    'onboarding.heardFrom': '¿Dónde nos conociste?',
    'onboarding.heardFrom.social': 'Redes Sociales',
    'onboarding.heardFrom.friends': 'Amigos',
    'onboarding.heardFrom.other': 'Otro',
    'onboarding.triedOtherApps': '¿Has probado otras apps de nutrición?',
    'onboarding.triedOtherApps.yes': 'Sí',
    'onboarding.triedOtherApps.no': 'No',
    'onboarding.height': 'Altura',
    'onboarding.heightQuestion': '¿Cuál es tu altura?',
    'onboarding.heightDescription': 'Esto se usará para calibrar tu plan personalizado.',
    'onboarding.weight': 'Peso',
    'onboarding.weightQuestion': '¿Cuál es tu peso?',
    'onboarding.weightDescription': 'Esto se usará para calibrar tu plan personalizado.',
    'onboarding.age': 'Edad',
    'onboarding.ageQuestion': '¿Cuál es tu edad?',
    'onboarding.ageDescription': 'Esto se usará para calibrar tu plan personalizado.',
    'onboarding.yearsOld': 'años',
    'onboarding.goal': '¿Cuál es tu objetivo?',
    'onboarding.goalDescription': 'Esto nos ayuda a generar un plan para tu ingesta calórica.',
    'onboarding.goal.lose': 'Perder Peso',
    'onboarding.goal.maintain': 'Mantener Peso',
    'onboarding.goal.gain': 'Ganar Peso',
    'onboarding.desiredWeight': 'Peso Deseado',
    'onboarding.desiredWeightQuestion': '¿Cuál es tu peso deseado?',
    'onboarding.currentWeight': 'Peso actual',
    'onboarding.desiredWeightHintGain': 'Para ganar peso, el peso deseado debe ser mayor que {weight} {unit}',
    'onboarding.desiredWeightHintLose': 'Para perder peso, el peso deseado debe ser menor que {weight} {unit}',
    'onboarding.desiredWeightErrorGain': 'El peso deseado debe ser mayor que {weight} {unit}',
    'onboarding.desiredWeightErrorLose': 'El peso deseado debe ser menor que {weight} {unit}',
    'onboarding.referralCode': 'Código de Referencia',
    'onboarding.referralCodeQuestion': '¿Tienes un código de referencia? (Opcional)',
    'onboarding.referralCode.placeholder': 'Introduce código de referencia',
    'onboarding.referralCode.paste': 'Pegar',
    'onboarding.referralCode.skip': 'Puedes saltarte este paso si no tienes un código',
    'onboarding.referralCode.pasted': '¡Código pegado!',
    'onboarding.referralCode.pastedMessage': 'El código de referencia ha sido pegado',
    'onboarding.referralCode.empty': 'Sin contenido',
    'onboarding.referralCode.emptyMessage': 'El portapapeles está vacío',
    'onboarding.referralCode.error': 'Error',
    'onboarding.referralCode.errorMessage': 'Error al pegar del portapapeles',
    'onboarding.referralCode.clipboardNotAvailable': 'Portapapeles no disponible',
    'onboarding.referralCode.clipboardNotAvailableMessage': 'Por favor, reconstruye la app para habilitar el pegado. Por ahora, puedes escribir el código manualmente.',
    'onboarding.calorieGoal': 'Tu Objetivo de Calorías Diarias',
    'onboarding.calorieGoalDescription': 'Basado en tu perfil, este es el número de calorías que debes consumir diariamente para alcanzar tu objetivo.',
    'onboarding.kcalPerDay': 'kcal por día',
    'onboarding.calculating': 'Calculando tu plan...',
    'onboarding.calculatingDescription': 'Estamos preparando tu plan nutricional personalizado',
    'onboarding.macros': 'Macronutrientes',
    'onboarding.protein': 'Proteína',
    'onboarding.carbs': 'Carbohidratos',
    'onboarding.fat': 'Grasa',
    'onboarding.metabolicInfo': 'Información Metabólica',
    'onboarding.bmr': 'Tasa Metabólica Basal (BMR)',
    'onboarding.tdee': 'Gasto Energético Total Diario (TDEE)',
    'onboarding.premiumTitle': 'Desbloquea Premium',
    'onboarding.premiumDescription': '¡Obtén acceso a funciones avanzadas y desbloquea tu potencial completo!',
    'onboarding.premiumButton': 'Actualizar a Premium',
    'onboarding.premiumSkip': 'Tal vez más tarde',
    'onboarding.premiumFeature1': 'Chat Ilimitado',
    'onboarding.premiumFeature2': 'Análisis y Reportes Avanzados',
    'onboarding.premiumFeature3': 'Seguimiento Ilimitado de Comidas',
    'onboarding.premiumFeature4': 'Insignias y Logros Exclusivos',
    'onboarding.premiumFeature5': 'Sincronización en la Nube',
    'onboarding.premiumFeature6': 'Soporte Prioritario',
    'onboarding.rateAppTitle': '¡Valóranos!',
    'onboarding.rateAppDescription': 'Si estás disfrutando de Nuti, ¡por favor tómate un momento para valorarnos en Play Store!',
    'onboarding.rateAppButton': 'Valorar en Play Store',
    'onboarding.rateAppSkip': 'Tal vez más tarde',
    'onboarding.createAccount': 'Crear Cuenta',
    'onboarding.createAccountTitle': 'Crea tu cuenta',
    'onboarding.createAccountDescription': 'Elige cómo quieres crear tu cuenta',
    'onboarding.metric': 'Métrico',
    'onboarding.imperial': 'Imperial',
    'onboarding.metricCm': 'Métrico (cm)',
    'onboarding.imperialFtIn': 'Imperial (pies/pulgadas)',
    'onboarding.metricKg': 'Métrico (kg)',
    'onboarding.imperialLbs': 'Imperial (lbs)',
    'onboarding.back': 'Atrás',
    'onboarding.continue': 'Continuar',
    'onboarding.cancel': 'Cancelar',
    'onboarding.error': 'Error',
    'onboarding.errorFillAllFields': 'Por favor, completa todos los campos',
    'onboarding.errorPasswordsDontMatch': 'Las contraseñas no coinciden',
    'onboarding.errorPasswordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    
    // Dashboard
    'dashboard.greeting': '¡Hola, {name}!',
    'dashboard.howIsDay': '¿Cómo va tu día?',
    'dashboard.caloriesConsumed': 'Consumidas',
    'dashboard.caloriesRemaining': 'Restantes',
    'dashboard.caloriesGoal': 'Meta',
    'dashboard.mealsToday': 'Comidas de Hoy',
    'dashboard.noMeals': 'Aún no has registrado comidas hoy.',
    'dashboard.addFirstMeal': '¡Añade tu primera comida!',
    'dashboard.streak': 'Racha de Días',
    'dashboard.badges': 'Insignias',
    'dashboard.protein': 'Proteína',
    'dashboard.carbs': 'Carbohidratos',
    'dashboard.fat': 'Grasa',
    'dashboard.water': 'Agua',
    'dashboard.addWater': 'Añadir Agua',
    'dashboard.editWater': 'Editar Agua',
    'dashboard.waterAmount': 'Cantidad',
    'dashboard.waterTotal': 'Cantidad Total',
    'dashboard.waterAdded': 'Agua Añadida',
    'dashboard.waterAddedMessage': 'añadida con éxito',
    'dashboard.waterUpdated': 'Agua Actualizada',
    'dashboard.waterUpdatedMessage': 'Cantidad de agua actualizada con éxito',
    'dashboard.waterInvalidAmount': 'Por favor, introduce una cantidad válida',
    'dashboard.waterError': 'Error al añadir agua. Por favor, intenta de nuevo.',
    'dashboard.add': 'Añadir',
    'dashboard.deleteMeal': 'Eliminar Comida',
    'dashboard.deleteMealConfirm': '¿Estás seguro de que quieres eliminar esta comida?',
    'dashboard.delete': 'Eliminar',
    'dashboard.mealDeleted': 'Comida Eliminada',
    'dashboard.mealDeletedMessage': 'La comida ha sido eliminada exitosamente.',
    'dashboard.deleteMealError': 'Error al eliminar comida. Por favor, intenta de nuevo.',
    'dashboard.mealType': 'Tipo de Comida',
    'dashboard.dateTime': 'Fecha y Hora',
    'dashboard.calories': 'Calorías',
    'dashboard.macros': 'Macronutrientes',
    'dashboard.today': 'Hoy',
    
    // Progress
    'progress.title': 'Progreso',
    'progress.subtitle': 'Sigue tu progreso diario',
    'progress.caloriesToday': 'Calorías Hoy',
    'progress.dailyGoal': 'Meta diaria',
    'progress.configureGoal': 'Configura tu meta de calorías en el perfil',
    'progress.statistics': 'Estadísticas',
    'progress.currentWeight': 'Peso actual',
    'progress.height': 'Altura',
    'progress.myWeight': 'Mi peso',
    'progress.goal': 'Meta',
    'progress.nextWeighIn': 'Próxima pesada',
    'progress.dayStreak': 'Racha de días',
    'progress.90Days': '90 Días',
    'progress.6Months': '6 Meses',
    'progress.1Year': '1 Año',
    'progress.allTime': 'Todo el tiempo...',
    'progress.goalProgress': 'Progreso del Objetivo',
    'progress.ofGoal': 'de la meta',
    'progress.motivationalMessage': 'Empezar es la parte más difícil. ¡Estás listo para esto!',
    
    // Chat
    'chat.title': 'Ayuda Nuti',
    'chat.subtitle': 'Tu asistente nutricional',
    'chat.placeholder': 'Escribe tu mensaje...',
    'chat.loading': 'Cargando...',
    'chat.greeting': '¡Hola!',
    'chat.greetingMessage': 'Estoy aquí para ayudarte en tu viaje nutricional. ¿Cómo puedo ayudarte hoy?',
    'chat.limitReached': 'Límite alcanzado',
    'chat.limitMessage': '¡Actualiza a Premium para chat ilimitado!',
    'chat.error': 'Error',
    'chat.errorMessage': 'Error al comunicar con la IA',
    'chat.retry': 'Por favor, intenta de nuevo.',
    
    // Add Meal
    'addMeal.title': 'Añadir Comida',
    'addMeal.camera': 'Tomar Foto',
    'addMeal.cameraDescription': 'Toma una foto de tu comida',
    'addMeal.barcode': 'Escanear Código de Barras',
    'addMeal.barcodeDescription': 'Escanea el código de barras del producto',
    'addMeal.search': 'Buscar Alimento',
    'addMeal.searchDescription': 'Busca alimentos manualmente',
    'addMeal.editFood': 'Editar Alimento',
    'addMeal.editFoodDescription': 'Revisa y edita la información identificada',
    'addMeal.mealType': 'Tipo de Comida',
    'addMeal.foodName': 'Nombre del Alimento',
    'addMeal.foodNamePlaceholder': 'Nombre del alimento',
    'addMeal.calories': 'Calorías',
    'addMeal.protein': 'Proteína',
    'addMeal.carbs': 'Carbohidratos',
    'addMeal.fat': 'Grasa',
    'addMeal.saveMeal': 'Añadir Comida',
    'addMeal.analyzing': 'Analizando imagen...',
    'addMeal.error': 'Error',
    'addMeal.errorProcessing': 'Error al procesar imagen. Por favor, intenta de nuevo.',
    'addMeal.errorNotFood': 'Esta imagen no contiene comida. Por favor, sube una imagen de comida.',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Información Personal',
    'profile.language': 'Idioma',
    'profile.edit': 'Editar',
    'profile.save': 'Guardar',
    'profile.cancel': 'Cancelar',
    'profile.name': 'Nombre',
    'profile.weight': 'Peso',
    'profile.height': 'Altura',
    'profile.goal': 'Objetivo',
    'profile.badges': 'Insignias Desbloqueadas',
    'profile.streak': 'Racha Actual',
    'profile.streakDays': 'días consecutivos',
    'profile.plan': 'Plan Actual',
    'profile.plan.free': 'Gratis',
    'profile.plan.premium': '⭐ Premium',
    'profile.upgradePremium': 'Actualizar a Premium',
    'profile.referralCode.title': 'Código de Referencia',
    'profile.referralCode.description': 'Comparte tu código con amigos y gana recompensas',
    'profile.referralCode.copied': '¡Código Copiado!',
    'profile.referralCode.copiedMessage': 'El código de referencia ha sido copiado al portapapeles',
    'profile.referralCode.copyError': 'Error al copiar código',
    'profile.signOut': 'Cerrar Sesión',
    'profile.signOutConfirm': '¿Estás seguro de que quieres cerrar sesión?',
    'profile.signOutConfirmYes': 'Cerrar Sesión',
    'profile.signOutConfirmNo': 'Cancelar',
    'profile.updateSuccess': 'Perfil actualizado con éxito',
    'profile.updateError': 'Error al actualizar perfil',
    'profile.settings': 'Configuración',
    'profile.settings.notifications': 'Notificaciones',
    'profile.settings.privacy': 'Privacidad',
    'profile.settings.about': 'Acerca de',
    'profile.settings.terms': 'Términos y Condiciones',
    'profile.settings.privacyPolicy': 'Política de Privacidad',
    'profile.settings.version': 'Versión',
    'profile.settings.help': 'Ayuda y Soporte',
    'profile.settings.feedback': 'Enviar Comentarios',
    'profile.settings.madeWith': 'Hecho con ❤️ para tu salud',
    'profile.settings.dataSecure': 'Tus datos están seguros',
    'profile.settings.supportEmail': 'Email de Soporte',
    'profile.settings.featureRequest': 'Solicitud de Funcionalidad',
    'profile.settings.deleteAccount': '¿Eliminar Cuenta?',
    'profile.settings.deleteAccountConfirm': '¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer.',
    'profile.settings.delete': 'Eliminar',
    'profile.personalDetails': 'Detalles personales',
    'profile.goalAndWeight': 'Meta y peso actual',
    'profile.preferences': 'Preferencias',
    'profile.age': 'años',
    'profile.referralCode.invite': 'Invita a un amigo para ganar $',
    'profile.editName': 'Editar Nombre',
    'profile.namePlaceholder': 'Ingrese su nombre aquí',
    'profile.done': 'Listo',
    'profile.nameRequired': 'Por favor, ingrese un nombre',
    'profile.nameUpdated': 'Nombre actualizado con éxito',
    'profile.detailsUpdated': 'Detalles actualizados con éxito',
    'profile.fillAllFields': 'Por favor, complete todos los campos',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.yes': 'Sí',
    'common.no': 'No',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.chat': 'Chat',
    'nav.add': 'Ajouter',
    'nav.profile': 'Profil',
    'nav.progress': 'Progrès',
    
    // Welcome Screen
    'welcome.title': 'Bienvenue sur Nuti',
    'welcome.subtitle': 'Votre assistant nutritionnel personnel',
    'welcome.getStarted': 'Commencer',
    'welcome.alreadyRegistered': 'Déjà inscrit ? Connectez-vous',
    'welcome.selectLanguage': 'Sélectionner la Langue',
    
    // Auth
    'auth.signIn': 'Se connecter',
    'auth.signUp': "S'inscrire",
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.name': 'Nom',
    'auth.continueWithGoogle': 'Continuer avec Google',
    'auth.continueWithEmail': 'Continuer avec Email',
    'auth.or': 'ou',
    'auth.noAccount': "Vous n'avez pas de compte ?",
    'auth.hasAccount': 'Vous avez déjà un compte ?',
    'auth.wrongMethod': 'Ce compte a été créé avec {method}. Veuillez utiliser {method} pour vous connecter.',
    'auth.invalidCredentials': 'Email ou mot de passe invalide',
    'auth.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'auth.weakPassword': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.emailInUse': 'Cet email est déjà utilisé',
    
    // Onboarding
    'onboarding.gender': 'Genre',
    'onboarding.gender.male': 'Masculin',
    'onboarding.gender.female': 'Féminin',
    'onboarding.genderDescription': 'Cela nous aide à personnaliser votre expérience',
    'onboarding.workoutsPerWeek': 'Combien d\'entraînements par semaine ?',
    'onboarding.workoutsPerWeekDescription': 'Cela nous aide à calculer vos besoins caloriques',
    'onboarding.workouts.0-2': '0-2',
    'onboarding.workouts.0-2.description': 'Sédentaire',
    'onboarding.workouts.3-6': '3-6',
    'onboarding.workouts.3-6.description': 'Modérément Actif',
    'onboarding.workouts.6+': '6+',
    'onboarding.workouts.6+.description': 'Très Actif',
    'onboarding.heardFrom': 'Où nous avez-vous connu ?',
    'onboarding.heardFrom.social': 'Réseaux Sociaux',
    'onboarding.heardFrom.friends': 'Amis',
    'onboarding.heardFrom.other': 'Autre',
    'onboarding.triedOtherApps': 'Avez-vous essayé d\'autres applications de nutrition ?',
    'onboarding.triedOtherApps.yes': 'Oui',
    'onboarding.triedOtherApps.no': 'Non',
    'onboarding.height': 'Taille',
    'onboarding.heightQuestion': 'Quelle est votre taille ?',
    'onboarding.heightDescription': 'Cela sera utilisé pour calibrer votre plan personnalisé.',
    'onboarding.weight': 'Poids',
    'onboarding.weightQuestion': 'Quel est votre poids ?',
    'onboarding.weightDescription': 'Cela sera utilisé pour calibrer votre plan personnalisé.',
    'onboarding.age': 'Âge',
    'onboarding.ageQuestion': 'Quel est votre âge ?',
    'onboarding.ageDescription': 'Cela sera utilisé pour calibrer votre plan personnalisé.',
    'onboarding.yearsOld': 'ans',
    'onboarding.goal': 'Quel est votre objectif ?',
    'onboarding.goalDescription': 'Cela nous aide à générer un plan pour votre apport calorique.',
    'onboarding.goal.lose': 'Perdre du Poids',
    'onboarding.goal.maintain': 'Maintenir le Poids',
    'onboarding.goal.gain': 'Prendre du Poids',
    'onboarding.desiredWeight': 'Poids Désiré',
    'onboarding.desiredWeightQuestion': 'Quel est votre poids désiré ?',
    'onboarding.currentWeight': 'Poids actuel',
    'onboarding.desiredWeightHintGain': 'Pour prendre du poids, le poids désiré doit être supérieur à {weight} {unit}',
    'onboarding.desiredWeightHintLose': 'Pour perdre du poids, le poids désiré doit être inférieur à {weight} {unit}',
    'onboarding.desiredWeightErrorGain': 'Le poids désiré doit être supérieur à {weight} {unit}',
    'onboarding.desiredWeightErrorLose': 'Le poids désiré doit être inférieur à {weight} {unit}',
    'onboarding.referralCode': 'Code de Parrainage',
    'onboarding.referralCodeQuestion': 'Avez-vous un code de parrainage ? (Optionnel)',
    'onboarding.referralCode.placeholder': 'Entrez le code de parrainage',
    'onboarding.referralCode.paste': 'Coller',
    'onboarding.referralCode.skip': 'Vous pouvez ignorer cette étape si vous n\'avez pas de code',
    'onboarding.referralCode.pasted': 'Code collé !',
    'onboarding.referralCode.pastedMessage': 'Le code de parrainage a été collé',
    'onboarding.referralCode.empty': 'Aucun contenu',
    'onboarding.referralCode.emptyMessage': 'Le presse-papiers est vide',
    'onboarding.referralCode.error': 'Erreur',
    'onboarding.referralCode.errorMessage': 'Échec du collage depuis le presse-papiers',
    'onboarding.referralCode.clipboardNotAvailable': 'Presse-papiers non disponible',
    'onboarding.referralCode.clipboardNotAvailableMessage': 'Veuillez reconstruire l\'app pour activer le collage. Pour l\'instant, vous pouvez taper le code manuellement.',
    'onboarding.calorieGoal': 'Votre Objectif de Calories Quotidiennes',
    'onboarding.calorieGoalDescription': 'Basé sur votre profil, c\'est le nombre de calories que vous devriez consommer quotidiennement pour atteindre votre objectif.',
    'onboarding.kcalPerDay': 'kcal par jour',
    'onboarding.calculating': 'Calcul de votre plan...',
    'onboarding.calculatingDescription': 'Nous préparons votre plan nutritionnel personnalisé',
    'onboarding.macros': 'Macronutriments',
    'onboarding.protein': 'Protéine',
    'onboarding.carbs': 'Glucides',
    'onboarding.fat': 'Graisse',
    'onboarding.metabolicInfo': 'Informations Métaboliques',
    'onboarding.bmr': 'Taux Métabolique de Base (BMR)',
    'onboarding.tdee': 'Dépense Énergétique Totale Quotidienne (TDEE)',
    'onboarding.premiumTitle': 'Débloquez Premium',
    'onboarding.premiumDescription': 'Accédez à des fonctionnalités avancées et débloquez votre plein potentiel !',
    'onboarding.premiumButton': 'Passer à Premium',
    'onboarding.premiumSkip': 'Peut-être plus tard',
    'onboarding.premiumFeature1': 'Chat Illimité',
    'onboarding.premiumFeature2': 'Analyses et Rapports Avancés',
    'onboarding.premiumFeature3': 'Suivi Illimité des Repas',
    'onboarding.premiumFeature4': 'Badges et Réalisations Exclusives',
    'onboarding.premiumFeature5': 'Synchronisation Cloud',
    'onboarding.premiumFeature6': 'Support Prioritaire',
    'onboarding.rateAppTitle': 'Notez-nous !',
    'onboarding.rateAppDescription': 'Si vous appréciez Nuti, veuillez prendre un moment pour nous noter sur le Play Store !',
    'onboarding.rateAppButton': 'Noter sur Play Store',
    'onboarding.rateAppSkip': 'Peut-être plus tard',
    'onboarding.createAccount': 'Créer un Compte',
    'onboarding.createAccountTitle': 'Créez votre compte',
    'onboarding.createAccountDescription': 'Choisissez comment vous voulez créer votre compte',
    'onboarding.metric': 'Métrique',
    'onboarding.imperial': 'Impérial',
    'onboarding.metricCm': 'Métrique (cm)',
    'onboarding.imperialFtIn': 'Impérial (pieds/pouces)',
    'onboarding.metricKg': 'Métrique (kg)',
    'onboarding.imperialLbs': 'Impérial (lbs)',
    'onboarding.back': 'Retour',
    'onboarding.continue': 'Continuer',
    'onboarding.cancel': 'Annuler',
    'onboarding.error': 'Erreur',
    'onboarding.errorFillAllFields': 'Veuillez remplir tous les champs',
    'onboarding.errorPasswordsDontMatch': 'Les mots de passe ne correspondent pas',
    'onboarding.errorPasswordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    
    // Dashboard
    'dashboard.greeting': 'Bonjour, {name} !',
    'dashboard.howIsDay': 'Comment se passe votre journée ?',
    'dashboard.caloriesConsumed': 'Consommées',
    'dashboard.caloriesRemaining': 'Restantes',
    'dashboard.caloriesGoal': 'Objectif',
    'dashboard.mealsToday': 'Repas d\'Aujourd\'hui',
    'dashboard.noMeals': 'Vous n\'avez pas encore enregistré de repas aujourd\'hui.',
    'dashboard.addFirstMeal': 'Ajoutez votre premier repas !',
    'dashboard.streak': 'Série de Jours',
    'dashboard.badges': 'Badges',
    'dashboard.protein': 'Protéine',
    'dashboard.carbs': 'Glucides',
    'dashboard.fat': 'Graisse',
    'dashboard.water': 'Eau',
    'dashboard.addWater': 'Ajouter de l\'Eau',
    'dashboard.editWater': 'Modifier l\'Eau',
    'dashboard.waterAmount': 'Quantité',
    'dashboard.waterTotal': 'Quantité Totale',
    'dashboard.waterAdded': 'Eau Ajoutée',
    'dashboard.waterAddedMessage': 'ajoutée avec succès',
    'dashboard.waterUpdated': 'Eau Modifiée',
    'dashboard.waterUpdatedMessage': 'Quantité d\'eau modifiée avec succès',
    'dashboard.waterInvalidAmount': 'Veuillez entrer une quantité valide',
    'dashboard.waterError': 'Erreur lors de l\'ajout d\'eau. Veuillez réessayer.',
    'dashboard.add': 'Ajouter',
    'dashboard.deleteMeal': 'Supprimer le Repas',
    'dashboard.deleteMealConfirm': 'Êtes-vous sûr de vouloir supprimer ce repas?',
    'dashboard.delete': 'Supprimer',
    'dashboard.mealDeleted': 'Repas Supprimé',
    'dashboard.mealDeletedMessage': 'Le repas a été supprimé avec succès.',
    'dashboard.deleteMealError': 'Erreur lors de la suppression du repas. Veuillez réessayer.',
    'dashboard.mealType': 'Type de Repas',
    'dashboard.dateTime': 'Date et Heure',
    'dashboard.calories': 'Calories',
    'dashboard.macros': 'Macronutriments',
    'dashboard.today': "Aujourd'hui",
    
    // Progress
    'progress.title': 'Progrès',
    'progress.subtitle': 'Suivez votre progrès quotidien',
    'progress.caloriesToday': 'Calories Aujourd\'hui',
    'progress.dailyGoal': 'Objectif quotidien',
    'progress.configureGoal': 'Configurez votre objectif de calories dans le profil',
    'progress.statistics': 'Statistiques',
    'progress.currentWeight': 'Poids actuel',
    'progress.height': 'Taille',
    'progress.myWeight': 'Mon poids',
    'progress.goal': 'Objectif',
    'progress.nextWeighIn': 'Prochaine pesée',
    'progress.dayStreak': 'Série de jours',
    'progress.90Days': '90 Jours',
    'progress.6Months': '6 Mois',
    'progress.1Year': '1 An',
    'progress.allTime': 'Tout le temps...',
    'progress.goalProgress': 'Progrès de l\'Objectif',
    'progress.ofGoal': 'de l\'objectif',
    'progress.motivationalMessage': 'Commencer est la partie la plus difficile. Vous êtes prêt pour cela !',
    
    // Chat
    'chat.title': 'Aide Nuti',
    'chat.subtitle': 'Votre assistant nutritionnel',
    'chat.placeholder': 'Tapez votre message...',
    'chat.loading': 'Chargement...',
    'chat.greeting': 'Bonjour !',
    'chat.greetingMessage': 'Je suis là pour vous aider dans votre parcours nutritionnel. Comment puis-je vous aider aujourd\'hui ?',
    'chat.limitReached': 'Limite atteinte',
    'chat.limitMessage': 'Passez à Premium pour un chat illimité !',
    'chat.error': 'Erreur',
    'chat.errorMessage': 'Erreur de communication avec l\'IA',
    'chat.retry': 'Veuillez réessayer.',
    
    // Add Meal
    'addMeal.title': 'Ajouter un Repas',
    'addMeal.camera': 'Prendre une Photo',
    'addMeal.cameraDescription': 'Prenez une photo de votre repas',
    'addMeal.barcode': 'Scanner le Code-Barres',
    'addMeal.barcodeDescription': 'Scannez le code-barres du produit',
    'addMeal.search': 'Rechercher un Aliment',
    'addMeal.searchDescription': 'Recherchez des aliments manuellement',
    'addMeal.editFood': 'Modifier l\'Aliment',
    'addMeal.editFoodDescription': 'Vérifiez et modifiez les informations identifiées',
    'addMeal.mealType': 'Type de Repas',
    'addMeal.foodName': 'Nom de l\'Aliment',
    'addMeal.foodNamePlaceholder': 'Nom de l\'aliment',
    'addMeal.calories': 'Calories',
    'addMeal.protein': 'Protéine',
    'addMeal.carbs': 'Glucides',
    'addMeal.fat': 'Graisse',
    'addMeal.saveMeal': 'Ajouter le Repas',
    'addMeal.analyzing': 'Analyse de l\'image...',
    'addMeal.error': 'Erreur',
    'addMeal.errorProcessing': 'Erreur lors du traitement de l\'image. Veuillez réessayer.',
    'addMeal.errorNotFood': 'Cette image ne contient pas de nourriture. Veuillez télécharger une image de nourriture.',
    
    // Profile
    'profile.title': 'Profil',
    'profile.personalInfo': 'Informations Personnelles',
    'profile.language': 'Langue',
    'profile.edit': 'Modifier',
    'profile.save': 'Enregistrer',
    'profile.cancel': 'Annuler',
    'profile.name': 'Nom',
    'profile.weight': 'Poids',
    'profile.height': 'Taille',
    'profile.goal': 'Objectif',
    'profile.badges': 'Badges Débloqués',
    'profile.streak': 'Série Actuelle',
    'profile.streakDays': 'jours consécutifs',
    'profile.plan': 'Plan Actuel',
    'profile.plan.free': 'Gratuit',
    'profile.plan.premium': '⭐ Premium',
    'profile.upgradePremium': 'Passer à Premium',
    'profile.referralCode.title': 'Code de Parrainage',
    'profile.referralCode.description': 'Partagez votre code avec des amis et gagnez des récompenses',
    'profile.referralCode.copied': 'Code Copié !',
    'profile.referralCode.copiedMessage': 'Le code de parrainage a été copié dans le presse-papiers',
    'profile.referralCode.copyError': 'Erreur lors de la copie du code',
    'profile.signOut': 'Se déconnecter',
    'profile.signOutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'profile.signOutConfirmYes': 'Se déconnecter',
    'profile.signOutConfirmNo': 'Annuler',
    'profile.updateSuccess': 'Profil mis à jour avec succès',
    'profile.updateError': 'Erreur lors de la mise à jour du profil',
    'profile.settings': 'Paramètres',
    'profile.settings.notifications': 'Notifications',
    'profile.settings.privacy': 'Confidentialité',
    'profile.settings.about': 'À propos',
    'profile.settings.terms': 'Termes et Conditions',
    'profile.settings.privacyPolicy': 'Politique de Confidentialité',
    'profile.settings.version': 'Version',
    'profile.settings.help': 'Aide et Support',
    'profile.settings.feedback': 'Envoyer des Commentaires',
    'profile.settings.madeWith': 'Fait avec ❤️ pour votre santé',
    'profile.settings.dataSecure': 'Vos données sont sécurisées',
    'profile.settings.supportEmail': 'Email de Support',
    'profile.settings.featureRequest': 'Demande de Fonctionnalité',
    'profile.settings.deleteAccount': 'Supprimer le Compte?',
    'profile.settings.deleteAccountConfirm': 'Êtes-vous sûr de vouloir supprimer votre compte? Cette action ne peut pas être annulée.',
    'profile.settings.delete': 'Supprimer',
    'profile.personalDetails': 'Détails personnels',
    'profile.goalAndWeight': 'Objectif et poids actuel',
    'profile.preferences': 'Préférences',
    'profile.age': 'ans',
    'profile.referralCode.invite': 'Invitez un ami pour gagner $',
    'profile.editName': 'Modifier le Nom',
    'profile.namePlaceholder': 'Entrez votre nom ici',
    'profile.done': 'Terminé',
    'profile.nameRequired': 'Veuillez entrer un nom',
    'profile.nameUpdated': 'Nom mis à jour avec succès',
    'profile.detailsUpdated': 'Détails mis à jour avec succès',
    'profile.fillAllFields': 'Veuillez remplir tous les champs',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.chat': 'Chat',
    'nav.add': 'Hinzufügen',
    'nav.profile': 'Profil',
    'nav.progress': 'Fortschritt',
    
    // Welcome Screen
    'welcome.title': 'Willkommen bei Nuti',
    'welcome.subtitle': 'Ihr persönlicher Ernährungsassistent',
    'welcome.getStarted': 'Loslegen',
    'welcome.alreadyRegistered': 'Bereits registriert? Anmelden',
    'welcome.selectLanguage': 'Sprache Auswählen',
    
    // Auth
    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.name': 'Name',
    'auth.continueWithGoogle': 'Mit Google fortfahren',
    'auth.continueWithEmail': 'Mit E-Mail fortfahren',
    'auth.or': 'oder',
    'auth.noAccount': 'Haben Sie kein Konto?',
    'auth.hasAccount': 'Haben Sie bereits ein Konto?',
    'auth.wrongMethod': 'Dieses Konto wurde mit {method} erstellt. Bitte verwenden Sie {method} zum Anmelden.',
    'auth.invalidCredentials': 'Ungültige E-Mail oder Passwort',
    'auth.passwordMismatch': 'Passwörter stimmen nicht überein',
    'auth.weakPassword': 'Das Passwort muss mindestens 6 Zeichen lang sein',
    'auth.emailInUse': 'Diese E-Mail wird bereits verwendet',
    
    // Onboarding
    'onboarding.gender': 'Geschlecht',
    'onboarding.gender.male': 'Männlich',
    'onboarding.gender.female': 'Weiblich',
    'onboarding.genderDescription': 'Dies hilft uns, Ihre Erfahrung zu personalisieren',
    'onboarding.workoutsPerWeek': 'Wie viele Trainingseinheiten pro Woche?',
    'onboarding.workoutsPerWeekDescription': 'Dies hilft uns, Ihren Kalorienbedarf zu berechnen',
    'onboarding.workouts.0-2': '0-2',
    'onboarding.workouts.0-2.description': 'Sitzend',
    'onboarding.workouts.3-6': '3-6',
    'onboarding.workouts.3-6.description': 'Mäßig Aktiv',
    'onboarding.workouts.6+': '6+',
    'onboarding.workouts.6+.description': 'Sehr Aktiv',
    'onboarding.heardFrom': 'Wo haben Sie von uns gehört?',
    'onboarding.heardFrom.social': 'Soziale Medien',
    'onboarding.heardFrom.friends': 'Freunde',
    'onboarding.heardFrom.other': 'Andere',
    'onboarding.triedOtherApps': 'Haben Sie andere Ernährungs-Apps ausprobiert?',
    'onboarding.triedOtherApps.yes': 'Ja',
    'onboarding.triedOtherApps.no': 'Nein',
    'onboarding.height': 'Größe',
    'onboarding.heightQuestion': 'Wie groß sind Sie?',
    'onboarding.heightDescription': 'Dies wird verwendet, um Ihren personalisierten Plan zu kalibrieren.',
    'onboarding.weight': 'Gewicht',
    'onboarding.weightQuestion': 'Wie viel wiegen Sie?',
    'onboarding.weightDescription': 'Dies wird verwendet, um Ihren personalisierten Plan zu kalibrieren.',
    'onboarding.age': 'Alter',
    'onboarding.ageQuestion': 'Wie alt sind Sie?',
    'onboarding.ageDescription': 'Dies wird verwendet, um Ihren personalisierten Plan zu kalibrieren.',
    'onboarding.yearsOld': 'Jahre alt',
    'onboarding.goal': 'Was ist Ihr Ziel?',
    'onboarding.goalDescription': 'Dies hilft uns, einen Plan für Ihre Kalorienaufnahme zu erstellen.',
    'onboarding.goal.lose': 'Gewicht Verlieren',
    'onboarding.goal.maintain': 'Gewicht Halten',
    'onboarding.goal.gain': 'Gewicht Zunehmen',
    'onboarding.desiredWeight': 'Gewünschtes Gewicht',
    'onboarding.desiredWeightQuestion': 'Wie viel möchten Sie wiegen?',
    'onboarding.currentWeight': 'Aktuelles Gewicht',
    'onboarding.desiredWeightHintGain': 'Um Gewicht zuzunehmen, muss das gewünschte Gewicht größer als {weight} {unit} sein',
    'onboarding.desiredWeightHintLose': 'Um Gewicht zu verlieren, muss das gewünschte Gewicht kleiner als {weight} {unit} sein',
    'onboarding.desiredWeightErrorGain': 'Das gewünschte Gewicht muss größer als {weight} {unit} sein',
    'onboarding.desiredWeightErrorLose': 'Das gewünschte Gewicht muss kleiner als {weight} {unit} sein',
    'onboarding.referralCode': 'Empfehlungscode',
    'onboarding.referralCodeQuestion': 'Haben Sie einen Empfehlungscode? (Optional)',
    'onboarding.referralCode.placeholder': 'Empfehlungscode eingeben',
    'onboarding.referralCode.paste': 'Einfügen',
    'onboarding.referralCode.skip': 'Sie können diesen Schritt überspringen, wenn Sie keinen Code haben',
    'onboarding.referralCode.pasted': 'Code eingefügt!',
    'onboarding.referralCode.pastedMessage': 'Der Empfehlungscode wurde eingefügt',
    'onboarding.referralCode.empty': 'Kein Inhalt',
    'onboarding.referralCode.emptyMessage': 'Die Zwischenablage ist leer',
    'onboarding.referralCode.error': 'Fehler',
    'onboarding.referralCode.errorMessage': 'Fehler beim Einfügen aus der Zwischenablage',
    'onboarding.referralCode.clipboardNotAvailable': 'Zwischenablage nicht verfügbar',
    'onboarding.referralCode.clipboardNotAvailableMessage': 'Bitte erstellen Sie die App neu, um das Einfügen zu aktivieren. Für jetzt können Sie den Code manuell eingeben.',
    'onboarding.calorieGoal': 'Ihr Tägliches Kalorienziel',
    'onboarding.calorieGoalDescription': 'Basierend auf Ihrem Profil ist dies die Anzahl der Kalorien, die Sie täglich konsumieren sollten, um Ihr Ziel zu erreichen.',
    'onboarding.kcalPerDay': 'kcal pro Tag',
    'onboarding.calculating': 'Berechnung Ihres Plans...',
    'onboarding.calculatingDescription': 'Wir bereiten Ihren personalisierten Ernährungsplan vor',
    'onboarding.macros': 'Makronährstoffe',
    'onboarding.protein': 'Protein',
    'onboarding.carbs': 'Kohlenhydrate',
    'onboarding.fat': 'Fett',
    'onboarding.metabolicInfo': 'Metabolische Informationen',
    'onboarding.bmr': 'Grundumsatz (BMR)',
    'onboarding.tdee': 'Gesamter Täglicher Energieverbrauch (TDEE)',
    'onboarding.premiumTitle': 'Premium Freischalten',
    'onboarding.premiumDescription': 'Erhalten Sie Zugang zu erweiterten Funktionen und schalten Sie Ihr volles Potenzial frei!',
    'onboarding.premiumButton': 'Auf Premium Upgraden',
    'onboarding.premiumSkip': 'Vielleicht später',
    'onboarding.premiumFeature1': 'Unbegrenzter Chat',
    'onboarding.premiumFeature2': 'Erweiterte Analysen & Berichte',
    'onboarding.premiumFeature3': 'Unbegrenzte Mahlzeitenverfolgung',
    'onboarding.premiumFeature4': 'Exklusive Abzeichen & Erfolge',
    'onboarding.premiumFeature5': 'Cloud-Synchronisierung',
    'onboarding.premiumFeature6': 'Prioritäts-Support',
    'onboarding.rateAppTitle': 'Bewerten Sie uns!',
    'onboarding.rateAppDescription': 'Wenn Sie Nuti genießen, nehmen Sie sich bitte einen Moment Zeit, um uns im Play Store zu bewerten!',
    'onboarding.rateAppButton': 'Im Play Store Bewerten',
    'onboarding.rateAppSkip': 'Vielleicht später',
    'onboarding.createAccount': 'Konto Erstellen',
    'onboarding.createAccountTitle': 'Erstellen Sie Ihr Konto',
    'onboarding.createAccountDescription': 'Wählen Sie, wie Sie Ihr Konto erstellen möchten',
    'onboarding.metric': 'Metrisch',
    'onboarding.imperial': 'Imperial',
    'onboarding.metricCm': 'Metrisch (cm)',
    'onboarding.imperialFtIn': 'Imperial (Fuß/Zoll)',
    'onboarding.metricKg': 'Metrisch (kg)',
    'onboarding.imperialLbs': 'Imperial (lbs)',
    'onboarding.back': 'Zurück',
    'onboarding.continue': 'Weiter',
    'onboarding.cancel': 'Abbrechen',
    'onboarding.error': 'Fehler',
    'onboarding.errorFillAllFields': 'Bitte füllen Sie alle Felder aus',
    'onboarding.errorPasswordsDontMatch': 'Die Passwörter stimmen nicht überein',
    'onboarding.errorPasswordTooShort': 'Das Passwort muss mindestens 6 Zeichen lang sein',
    
    // Dashboard
    'dashboard.greeting': 'Hallo, {name}!',
    'dashboard.howIsDay': 'Wie läuft Ihr Tag?',
    'dashboard.caloriesConsumed': 'Verbraucht',
    'dashboard.caloriesRemaining': 'Verbleibend',
    'dashboard.caloriesGoal': 'Ziel',
    'dashboard.mealsToday': 'Mahlzeiten Heute',
    'dashboard.noMeals': 'Sie haben heute noch keine Mahlzeiten registriert.',
    'dashboard.addFirstMeal': 'Fügen Sie Ihre erste Mahlzeit hinzu!',
    'dashboard.streak': 'Tage in Folge',
    'dashboard.badges': 'Abzeichen',
    'dashboard.protein': 'Protein',
    'dashboard.carbs': 'Kohlenhydrate',
    'dashboard.fat': 'Fett',
    'dashboard.water': 'Wasser',
    'dashboard.addWater': 'Wasser Hinzufügen',
    'dashboard.editWater': 'Wasser Bearbeiten',
    'dashboard.waterAmount': 'Menge',
    'dashboard.waterTotal': 'Gesamtmenge',
    'dashboard.waterAdded': 'Wasser Hinzugefügt',
    'dashboard.waterAddedMessage': 'erfolgreich hinzugefügt',
    'dashboard.waterUpdated': 'Wasser Aktualisiert',
    'dashboard.waterUpdatedMessage': 'Wassermenge erfolgreich aktualisiert',
    'dashboard.waterInvalidAmount': 'Bitte geben Sie eine gültige Menge ein',
    'dashboard.waterError': 'Fehler beim Hinzufügen von Wasser. Bitte versuchen Sie es erneut.',
    'dashboard.add': 'Hinzufügen',
    'dashboard.deleteMeal': 'Mahlzeit Löschen',
    'dashboard.deleteMealConfirm': 'Sind Sie sicher, dass Sie diese Mahlzeit löschen möchten?',
    'dashboard.delete': 'Löschen',
    'dashboard.mealDeleted': 'Mahlzeit Gelöscht',
    'dashboard.mealDeletedMessage': 'Die Mahlzeit wurde erfolgreich gelöscht.',
    'dashboard.deleteMealError': 'Fehler beim Löschen der Mahlzeit. Bitte versuchen Sie es erneut.',
    'dashboard.mealType': 'Mahlzeittyp',
    'dashboard.dateTime': 'Datum und Uhrzeit',
    'dashboard.calories': 'Kalorien',
    'dashboard.macros': 'Makronährstoffe',
    'dashboard.today': 'Heute',
    
    // Progress
    'progress.title': 'Fortschritt',
    'progress.subtitle': 'Verfolgen Sie Ihren täglichen Fortschritt',
    'progress.caloriesToday': 'Kalorien Heute',
    'progress.dailyGoal': 'Tagesziel',
    'progress.configureGoal': 'Konfigurieren Sie Ihr Kalorienziel im Profil',
    'progress.statistics': 'Statistiken',
    'progress.currentWeight': 'Aktuelles Gewicht',
    'progress.height': 'Größe',
    'progress.myWeight': 'Mein Gewicht',
    'progress.goal': 'Ziel',
    'progress.nextWeighIn': 'Nächstes Wiegen',
    'progress.dayStreak': 'Tages-Serie',
    'progress.90Days': '90 Tage',
    'progress.6Months': '6 Monate',
    'progress.1Year': '1 Jahr',
    'progress.allTime': 'Gesamte Zeit...',
    'progress.goalProgress': 'Fortschritt des Ziels',
    'progress.ofGoal': 'des Ziels',
    'progress.motivationalMessage': 'Anfangen ist der schwierigste Teil. Sie sind bereit dafür!',
    
    // Chat
    'chat.title': 'Hilfe Nuti',
    'chat.subtitle': 'Ihr Ernährungsassistent',
    'chat.placeholder': 'Geben Sie Ihre Nachricht ein...',
    'chat.loading': 'Lädt...',
    'chat.greeting': 'Hallo!',
    'chat.greetingMessage': 'Ich bin hier, um Ihnen auf Ihrer Ernährungsreise zu helfen. Wie kann ich Ihnen heute helfen?',
    'chat.limitReached': 'Limit erreicht',
    'chat.limitMessage': 'Upgraden Sie auf Premium für unbegrenzten Chat!',
    'chat.error': 'Fehler',
    'chat.errorMessage': 'Fehler bei der Kommunikation mit der KI',
    'chat.retry': 'Bitte versuchen Sie es erneut.',
    
    // Add Meal
    'addMeal.title': 'Mahlzeit Hinzufügen',
    'addMeal.camera': 'Foto Aufnehmen',
    'addMeal.cameraDescription': 'Machen Sie ein Foto Ihrer Mahlzeit',
    'addMeal.barcode': 'Barcode Scannen',
    'addMeal.barcodeDescription': 'Scannen Sie den Produktbarcode',
    'addMeal.search': 'Essen Suchen',
    'addMeal.searchDescription': 'Suchen Sie manuell nach Lebensmitteln',
    'addMeal.editFood': 'Essen Bearbeiten',
    'addMeal.editFoodDescription': 'Überprüfen und bearbeiten Sie die identifizierten Informationen',
    'addMeal.mealType': 'Mahlzeittyp',
    'addMeal.foodName': 'Essensname',
    'addMeal.foodNamePlaceholder': 'Essensname',
    'addMeal.calories': 'Kalorien',
    'addMeal.protein': 'Protein',
    'addMeal.carbs': 'Kohlenhydrate',
    'addMeal.fat': 'Fett',
    'addMeal.saveMeal': 'Mahlzeit Hinzufügen',
    'addMeal.analyzing': 'Bild analysieren...',
    'addMeal.error': 'Fehler',
    'addMeal.errorProcessing': 'Fehler beim Verarbeiten des Bildes. Bitte versuchen Sie es erneut.',
    'addMeal.errorNotFood': 'Dieses Bild enthält kein Essen. Bitte laden Sie ein Bild von Essen hoch.',
    
    // Profile
    'profile.title': 'Profil',
    'profile.personalInfo': 'Persönliche Informationen',
    'profile.language': 'Sprache',
    'profile.edit': 'Bearbeiten',
    'profile.save': 'Speichern',
    'profile.cancel': 'Abbrechen',
    'profile.name': 'Name',
    'profile.weight': 'Gewicht',
    'profile.height': 'Größe',
    'profile.goal': 'Ziel',
    'profile.badges': 'Freigeschaltete Abzeichen',
    'profile.streak': 'Aktuelle Serie',
    'profile.streakDays': 'Tage in Folge',
    'profile.plan': 'Aktueller Plan',
    'profile.plan.free': 'Kostenlos',
    'profile.plan.premium': '⭐ Premium',
    'profile.upgradePremium': 'Auf Premium upgraden',
    'profile.referralCode.title': 'Empfehlungscode',
    'profile.referralCode.description': 'Teilen Sie Ihren Code mit Freunden und verdienen Sie Belohnungen',
    'profile.referralCode.copied': 'Code Kopiert!',
    'profile.referralCode.copiedMessage': 'Der Empfehlungscode wurde in die Zwischenablage kopiert',
    'profile.referralCode.copyError': 'Fehler beim Kopieren des Codes',
    'profile.signOut': 'Abmelden',
    'profile.signOutConfirm': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    'profile.signOutConfirmYes': 'Abmelden',
    'profile.signOutConfirmNo': 'Abbrechen',
    'profile.updateSuccess': 'Profil erfolgreich aktualisiert',
    'profile.updateError': 'Fehler beim Aktualisieren des Profils',
    'profile.settings': 'Einstellungen',
    'profile.settings.notifications': 'Benachrichtigungen',
    'profile.settings.privacy': 'Datenschutz',
    'profile.settings.about': 'Über',
    'profile.settings.terms': 'Allgemeine Geschäftsbedingungen',
    'profile.settings.privacyPolicy': 'Datenschutzrichtlinie',
    'profile.settings.version': 'Version',
    'profile.settings.help': 'Hilfe & Support',
    'profile.settings.feedback': 'Feedback senden',
    'profile.settings.madeWith': 'Mit ❤️ für Ihre Gesundheit gemacht',
    'profile.settings.dataSecure': 'Ihre Daten sind sicher',
    'profile.settings.supportEmail': 'Support-E-Mail',
    'profile.settings.featureRequest': 'Feature-Anfrage',
    'profile.settings.deleteAccount': 'Konto löschen?',
    'profile.settings.deleteAccountConfirm': 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'profile.settings.delete': 'Löschen',
    'profile.personalDetails': 'Persönliche Details',
    'profile.goalAndWeight': 'Ziel und aktuelles Gewicht',
    'profile.preferences': 'Einstellungen',
    'profile.age': 'Jahre alt',
    'profile.referralCode.invite': 'Laden Sie einen Freund ein, um $ zu verdienen',
    'profile.editName': 'Namen Bearbeiten',
    'profile.namePlaceholder': 'Geben Sie hier Ihren Namen ein',
    'profile.done': 'Fertig',
    'profile.nameRequired': 'Bitte geben Sie einen Namen ein',
    'profile.nameUpdated': 'Name erfolgreich aktualisiert',
    'profile.detailsUpdated': 'Details erfolgreich aktualisiert',
    'profile.fillAllFields': 'Bitte füllen Sie alle Felder aus',
    
    // Common
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.chat': 'Chat',
    'nav.add': 'Aggiungi',
    'nav.profile': 'Profilo',
    'nav.progress': 'Progresso',
    
    // Welcome Screen
    'welcome.title': 'Benvenuto su Nuti',
    'welcome.subtitle': 'Il tuo assistente nutrizionale personale',
    'welcome.getStarted': 'Inizia',
    'welcome.alreadyRegistered': 'Già registrato? Accedi',
    'welcome.selectLanguage': 'Seleziona Lingua',
    
    // Auth
    'auth.signIn': 'Accedi',
    'auth.signUp': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma Password',
    'auth.name': 'Nome',
    'auth.continueWithGoogle': 'Continua con Google',
    'auth.continueWithEmail': 'Continua con Email',
    'auth.or': 'o',
    'auth.noAccount': 'Non hai un account?',
    'auth.hasAccount': 'Hai già un account?',
    'auth.wrongMethod': 'Questo account è stato creato con {method}. Per favore, usa {method} per accedere.',
    'auth.invalidCredentials': 'Email o password non validi',
    'auth.passwordMismatch': 'Le password non corrispondono',
    'auth.weakPassword': 'La password deve contenere almeno 6 caratteri',
    'auth.emailInUse': 'Questa email è già in uso',
    
    // Onboarding
    'onboarding.gender': 'Genere',
    'onboarding.gender.male': 'Maschio',
    'onboarding.gender.female': 'Femmina',
    'onboarding.genderDescription': 'Questo ci aiuta a personalizzare la tua esperienza',
    'onboarding.workoutsPerWeek': 'Quanti allenamenti a settimana?',
    'onboarding.workoutsPerWeekDescription': 'Questo ci aiuta a calcolare le tue esigenze caloriche',
    'onboarding.workouts.0-2': '0-2',
    'onboarding.workouts.0-2.description': 'Sedentario',
    'onboarding.workouts.3-6': '3-6',
    'onboarding.workouts.3-6.description': 'Moderatamente Attivo',
    'onboarding.workouts.6+': '6+',
    'onboarding.workouts.6+.description': 'Molto Attivo',
    'onboarding.heardFrom': 'Dove ci hai conosciuto?',
    'onboarding.heardFrom.social': 'Social Media',
    'onboarding.heardFrom.friends': 'Amici',
    'onboarding.heardFrom.other': 'Altro',
    'onboarding.triedOtherApps': 'Hai provato altre app nutrizionali?',
    'onboarding.triedOtherApps.yes': 'Sì',
    'onboarding.triedOtherApps.no': 'No',
    'onboarding.height': 'Altezza',
    'onboarding.heightQuestion': 'Qual è la tua altezza?',
    'onboarding.heightDescription': 'Questo sarà usato per calibrare il tuo piano personalizzato.',
    'onboarding.weight': 'Peso',
    'onboarding.weightQuestion': 'Qual è il tuo peso?',
    'onboarding.weightDescription': 'Questo sarà usato per calibrare il tuo piano personalizzato.',
    'onboarding.age': 'Età',
    'onboarding.ageQuestion': 'Qual è la tua età?',
    'onboarding.ageDescription': 'Questo sarà usato per calibrare il tuo piano personalizzato.',
    'onboarding.yearsOld': 'anni',
    'onboarding.goal': 'Qual è il tuo obiettivo?',
    'onboarding.goalDescription': 'Questo ci aiuta a generare un piano per il tuo apporto calorico.',
    'onboarding.goal.lose': 'Perdere Peso',
    'onboarding.goal.maintain': 'Mantenere Peso',
    'onboarding.goal.gain': 'Aumentare Peso',
    'onboarding.desiredWeight': 'Peso Desiderato',
    'onboarding.desiredWeightQuestion': 'Qual è il tuo peso desiderato?',
    'onboarding.currentWeight': 'Peso attuale',
    'onboarding.desiredWeightHintGain': 'Per aumentare di peso, il peso desiderato deve essere maggiore di {weight} {unit}',
    'onboarding.desiredWeightHintLose': 'Per perdere peso, il peso desiderato deve essere minore di {weight} {unit}',
    'onboarding.desiredWeightErrorGain': 'Il peso desiderato deve essere maggiore di {weight} {unit}',
    'onboarding.desiredWeightErrorLose': 'Il peso desiderato deve essere minore di {weight} {unit}',
    'onboarding.referralCode': 'Codice di Riferimento',
    'onboarding.referralCodeQuestion': 'Hai un codice di riferimento? (Opzionale)',
    'onboarding.referralCode.placeholder': 'Inserisci codice di riferimento',
    'onboarding.referralCode.paste': 'Incolla',
    'onboarding.referralCode.skip': 'Puoi saltare questo passaggio se non hai un codice',
    'onboarding.referralCode.pasted': 'Codice incollato!',
    'onboarding.referralCode.pastedMessage': 'Il codice di riferimento è stato incollato',
    'onboarding.referralCode.empty': 'Nessun contenuto',
    'onboarding.referralCode.emptyMessage': 'Gli appunti sono vuoti',
    'onboarding.referralCode.error': 'Errore',
    'onboarding.referralCode.errorMessage': 'Errore nell\'incollare dagli appunti',
    'onboarding.referralCode.clipboardNotAvailable': 'Appunti non disponibili',
    'onboarding.referralCode.clipboardNotAvailableMessage': 'Per favore, ricostruisci l\'app per abilitare l\'incollaggio. Per ora, puoi digitare il codice manualmente.',
    'onboarding.calorieGoal': 'Il Tuo Obiettivo Calorico Giornaliero',
    'onboarding.calorieGoalDescription': 'Basato sul tuo profilo, questo è il numero di calorie che dovresti consumare quotidianamente per raggiungere il tuo obiettivo.',
    'onboarding.kcalPerDay': 'kcal al giorno',
    'onboarding.calculating': 'Calcolo del tuo piano...',
    'onboarding.calculatingDescription': 'Stiamo preparando il tuo piano nutrizionale personalizzato',
    'onboarding.macros': 'Macronutrienti',
    'onboarding.protein': 'Proteina',
    'onboarding.carbs': 'Carboidrati',
    'onboarding.fat': 'Grasso',
    'onboarding.metabolicInfo': 'Informazioni Metaboliche',
    'onboarding.bmr': 'Metabolismo Basale (BMR)',
    'onboarding.tdee': 'Dispendio Energetico Totale Giornaliero (TDEE)',
    'onboarding.premiumTitle': 'Sblocca Premium',
    'onboarding.premiumDescription': 'Ottieni accesso a funzionalità avanzate e sblocca il tuo pieno potenziale!',
    'onboarding.premiumButton': 'Passa a Premium',
    'onboarding.premiumSkip': 'Forse più tardi',
    'onboarding.premiumFeature1': 'Chat Illimitata',
    'onboarding.premiumFeature2': 'Analisi e Report Avanzati',
    'onboarding.premiumFeature3': 'Tracciamento Illimitato dei Pasti',
    'onboarding.premiumFeature4': 'Badge e Conquiste Esclusive',
    'onboarding.premiumFeature5': 'Sincronizzazione Cloud',
    'onboarding.premiumFeature6': 'Supporto Prioritario',
    'onboarding.rateAppTitle': 'Valutaci!',
    'onboarding.rateAppDescription': 'Se ti piace Nuti, per favore prenditi un momento per valutarci su Play Store!',
    'onboarding.rateAppButton': 'Valuta su Play Store',
    'onboarding.rateAppSkip': 'Forse più tardi',
    'onboarding.createAccount': 'Crea Account',
    'onboarding.createAccountTitle': 'Crea il tuo account',
    'onboarding.createAccountDescription': 'Scegli come vuoi creare il tuo account',
    'onboarding.metric': 'Metrico',
    'onboarding.imperial': 'Imperiale',
    'onboarding.metricCm': 'Metrico (cm)',
    'onboarding.imperialFtIn': 'Imperiale (piedi/pollici)',
    'onboarding.metricKg': 'Metrico (kg)',
    'onboarding.imperialLbs': 'Imperiale (lbs)',
    'onboarding.back': 'Indietro',
    'onboarding.continue': 'Continua',
    'onboarding.cancel': 'Annulla',
    'onboarding.error': 'Errore',
    'onboarding.errorFillAllFields': 'Per favore, compila tutti i campi',
    'onboarding.errorPasswordsDontMatch': 'Le password non corrispondono',
    'onboarding.errorPasswordTooShort': 'La password deve contenere almeno 6 caratteri',
    
    // Dashboard
    'dashboard.greeting': 'Ciao, {name}!',
    'dashboard.howIsDay': 'Come va la tua giornata?',
    'dashboard.caloriesConsumed': 'Consumate',
    'dashboard.caloriesRemaining': 'Rimanenti',
    'dashboard.caloriesGoal': 'Obiettivo',
    'dashboard.mealsToday': 'Pasti di Oggi',
    'dashboard.noMeals': 'Non hai ancora registrato pasti oggi.',
    'dashboard.addFirstMeal': 'Aggiungi il tuo primo pasto!',
    'dashboard.streak': 'Giorni Consecutivi',
    'dashboard.badges': 'Badge',
    'dashboard.protein': 'Proteina',
    'dashboard.carbs': 'Carboidrati',
    'dashboard.fat': 'Grasso',
    'dashboard.water': 'Acqua',
    'dashboard.addWater': 'Aggiungi Acqua',
    'dashboard.editWater': 'Modifica Acqua',
    'dashboard.waterAmount': 'Quantità',
    'dashboard.waterTotal': 'Quantità Totale',
    'dashboard.waterAdded': 'Acqua Aggiunta',
    'dashboard.waterAddedMessage': 'aggiunta con successo',
    'dashboard.waterUpdated': 'Acqua Aggiornata',
    'dashboard.waterUpdatedMessage': 'Quantità di acqua aggiornata con successo',
    'dashboard.waterInvalidAmount': 'Inserisci una quantità valida',
    'dashboard.waterError': 'Errore nell\'aggiunta dell\'acqua. Riprova.',
    'dashboard.add': 'Aggiungi',
    'dashboard.deleteMeal': 'Elimina Pasto',
    'dashboard.deleteMealConfirm': 'Sei sicuro di voler eliminare questo pasto?',
    'dashboard.delete': 'Elimina',
    'dashboard.mealDeleted': 'Pasto Eliminato',
    'dashboard.mealDeletedMessage': 'Il pasto è stato eliminato con successo.',
    'dashboard.deleteMealError': 'Errore nell\'eliminazione del pasto. Riprova.',
    'dashboard.mealType': 'Tipo di Pasto',
    'dashboard.dateTime': 'Data e Ora',
    'dashboard.calories': 'Calorie',
    'dashboard.macros': 'Macronutrienti',
    'dashboard.today': 'Oggi',
    
    // Progress
    'progress.title': 'Progresso',
    'progress.subtitle': 'Segui il tuo progresso quotidiano',
    'progress.caloriesToday': 'Calorie Oggi',
    'progress.dailyGoal': 'Obiettivo giornaliero',
    'progress.configureGoal': 'Configura il tuo obiettivo calorico nel profilo',
    'progress.statistics': 'Statistiche',
    'progress.currentWeight': 'Peso attuale',
    'progress.height': 'Altezza',
    'progress.myWeight': 'Il mio peso',
    'progress.goal': 'Obiettivo',
    'progress.nextWeighIn': 'Prossima pesata',
    'progress.dayStreak': 'Serie di giorni',
    'progress.90Days': '90 Giorni',
    'progress.6Months': '6 Mesi',
    'progress.1Year': '1 Anno',
    'progress.allTime': 'Tutto il tempo...',
    'progress.goalProgress': 'Progresso dell\'Obiettivo',
    'progress.ofGoal': 'dell\'obiettivo',
    'progress.motivationalMessage': 'Iniziare è la parte più difficile. Sei pronto per questo!',
    
    // Chat
    'chat.title': 'Aiuto Nuti',
    'chat.subtitle': 'Il tuo assistente nutrizionale',
    'chat.placeholder': 'Scrivi il tuo messaggio...',
    'chat.loading': 'Caricamento...',
    'chat.greeting': 'Ciao!',
    'chat.greetingMessage': 'Sono qui per aiutarti nel tuo percorso nutrizionale. Come posso aiutarti oggi?',
    'chat.limitReached': 'Limite raggiunto',
    'chat.limitMessage': 'Passa a Premium per chat illimitato!',
    'chat.error': 'Errore',
    'chat.errorMessage': 'Errore nella comunicazione con l\'IA',
    'chat.retry': 'Per favore, riprova.',
    
    // Add Meal
    'addMeal.title': 'Aggiungi Pasto',
    'addMeal.camera': 'Scatta Foto',
    'addMeal.cameraDescription': 'Scatta una foto del tuo pasto',
    'addMeal.barcode': 'Scansiona Codice a Barre',
    'addMeal.barcodeDescription': 'Scansiona il codice a barre del prodotto',
    'addMeal.search': 'Cerca Cibo',
    'addMeal.searchDescription': 'Cerca cibo manualmente',
    'addMeal.editFood': 'Modifica Cibo',
    'addMeal.editFoodDescription': 'Rivedi e modifica le informazioni identificate',
    'addMeal.mealType': 'Tipo di Pasto',
    'addMeal.foodName': 'Nome del Cibo',
    'addMeal.foodNamePlaceholder': 'Nome del cibo',
    'addMeal.calories': 'Calorie',
    'addMeal.protein': 'Proteina',
    'addMeal.carbs': 'Carboidrati',
    'addMeal.fat': 'Grasso',
    'addMeal.saveMeal': 'Aggiungi Pasto',
    'addMeal.analyzing': 'Analizzando immagine...',
    'addMeal.error': 'Errore',
    'addMeal.errorProcessing': 'Errore nell\'elaborazione dell\'immagine. Riprova.',
    'addMeal.errorNotFood': 'Questa immagine non contiene cibo. Carica un\'immagine di cibo.',
    
    // Profile
    'profile.title': 'Profilo',
    'profile.personalInfo': 'Informazioni Personali',
    'profile.language': 'Lingua',
    'profile.edit': 'Modifica',
    'profile.save': 'Salva',
    'profile.cancel': 'Annulla',
    'profile.name': 'Nome',
    'profile.weight': 'Peso',
    'profile.height': 'Altezza',
    'profile.goal': 'Obiettivo',
    'profile.badges': 'Badge Sbloccati',
    'profile.streak': 'Serie Attuale',
    'profile.streakDays': 'giorni consecutivi',
    'profile.plan': 'Piano Attuale',
    'profile.plan.free': 'Gratuito',
    'profile.plan.premium': '⭐ Premium',
    'profile.upgradePremium': 'Passa a Premium',
    'profile.referralCode.title': 'Codice di Riferimento',
    'profile.referralCode.description': 'Condividi il tuo codice con gli amici e guadagna ricompense',
    'profile.referralCode.copied': 'Codice Copiato!',
    'profile.referralCode.copiedMessage': 'Il codice di riferimento è stato copiato negli appunti',
    'profile.referralCode.copyError': 'Errore nella copia del codice',
    'profile.signOut': 'Esci',
    'profile.signOutConfirm': 'Sei sicuro di voler uscire?',
    'profile.signOutConfirmYes': 'Esci',
    'profile.signOutConfirmNo': 'Annulla',
    'profile.updateSuccess': 'Profilo aggiornato con successo',
    'profile.updateError': 'Errore nell\'aggiornamento del profilo',
    'profile.settings': 'Impostazioni',
    'profile.settings.notifications': 'Notifiche',
    'profile.settings.privacy': 'Privacy',
    'profile.settings.about': 'Informazioni',
    'profile.settings.terms': 'Termini e Condizioni',
    'profile.settings.privacyPolicy': 'Informativa sulla Privacy',
    'profile.settings.version': 'Versione',
    'profile.settings.help': 'Aiuto e Supporto',
    'profile.settings.feedback': 'Invia Feedback',
    'profile.settings.madeWith': 'Fatto con ❤️ per la tua salute',
    'profile.settings.dataSecure': 'I tuoi dati sono sicuri',
    'profile.settings.supportEmail': 'Email di Supporto',
    'profile.settings.featureRequest': 'Richiesta Funzionalità',
    'profile.settings.deleteAccount': 'Eliminare Account?',
    'profile.settings.deleteAccountConfirm': 'Sei sicuro di voler eliminare il tuo account? Questa azione non può essere annullata.',
    'profile.settings.delete': 'Elimina',
    'profile.personalDetails': 'Dettagli personali',
    'profile.goalAndWeight': 'Obiettivo e peso attuale',
    'profile.preferences': 'Preferenze',
    'profile.age': 'anni',
    'profile.referralCode.invite': 'Invita un amico per guadagnare $',
    'profile.editName': 'Modifica Nome',
    'profile.namePlaceholder': 'Inserisci il nome qui',
    'profile.done': 'Fatto',
    'profile.nameRequired': 'Per favore, inserisci un nome',
    'profile.nameUpdated': 'Nome aggiornato con successo',
    'profile.detailsUpdated': 'Dettagli aggiornati con successo',
    'profile.fillAllFields': 'Si prega di compilare tutti i campi',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.close': 'Chiudi',
    'common.yes': 'Sì',
    'common.no': 'No',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const initializeLanguage = async () => {
      try {
        const savedLang = await AsyncStorage.getItem('appLanguage');
        const languageWasManuallySet = await AsyncStorage.getItem('languageManuallySet');
        // Se o idioma foi escolhido manualmente pelo utilizador, usar esse
        if (languageWasManuallySet === 'true' && savedLang && (savedLang === 'en' || savedLang === 'pt' || savedLang === 'es' || savedLang === 'fr' || savedLang === 'de' || savedLang === 'it')) {
          setLanguageState(savedLang as Language);
        } else {
          // Se não foi escolhido manualmente ou não existe, detectar idioma do dispositivo
          const deviceLang = getDeviceLanguage();
          setLanguageState(deviceLang);
          await AsyncStorage.setItem('appLanguage', deviceLang);
          // Marcar que ainda não foi escolhido manualmente
          await AsyncStorage.setItem('languageManuallySet', 'false');
        }
      } catch (error) {
        console.error('❌ Error initializing language:', error);
        // Fallback para inglês em caso de erro
        setLanguageState('en');
      } finally {
        setIsInitialized(true);
      }
    };
    
    initializeLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem('appLanguage', lang);
    // Marcar que o idioma foi escolhido manualmente pelo utilizador
    await AsyncStorage.setItem('languageManuallySet', 'true');
  };

  const t = (key: string): string => {
    const translation = translations[language]?.[key];
    if (!translation) {
      // Fallback para inglês se não encontrar tradução
      return translations['en'][key] || key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

